/* R2's phrases. One per line, strict JSON.
   t = the text ({name} = her name, {daysLeft} = days to 14 Oct)   lang = en | fr | beep  (+ four rare ru / kk greetings)
   mood = how R2 feels when he says it   tags = when he says it   weight = how often (normal phrases are about 3; the four Russian / Kazakh ones are 1)
   Weights keep the mix at about 45% English, 45% French, 5% beeps (the four Russian / Kazakh ones are well under 1%). Raise their weight to hear them more.
   Tags: hello jealous embarrassed scared dizzy flirty idle excited dreamy mischievous confused worried grateful bored playful determined tap1 tap2 tapspam tapangry forgive hello_morning hello_day hello_evening hello_night
   return_min return_hours return_day return_days bazaar_enter bazaar_poor bazaar_buy bazaar_locked quest gift pass game_start game_win game_lose
   quiz_right quiz_wrong gems sleepy wake dizzy still ignored countdown birthday about_her about_us distance droid mystery */
R2.register("phrases", {
  "list": [
    {"t": "Coucou !", "lang": "fr", "mood": "neutral", "tags": ["idle"], "weight": 3.0},
    {"t": "Je suis là.", "lang": "fr", "mood": "neutral", "tags": ["idle"], "weight": 3.0},
    {"t": "Tout va bien ?", "lang": "fr", "mood": "neutral", "tags": ["idle"], "weight": 3.0},
    {"t": "Comment va ta journée ?", "lang": "fr", "mood": "neutral", "tags": ["idle"], "weight": 3.0},
    {"t": "N'oublie pas de boire de l'eau.", "lang": "fr", "mood": "neutral", "tags": ["idle"], "weight": 3.0},
    {"t": "Raconte-moi quelque chose.", "lang": "fr", "mood": "neutral", "tags": ["idle"], "weight": 3.0},
    {"t": "Mes circuits sont contents.", "lang": "fr", "mood": "neutral", "tags": ["idle"], "weight": 3.0},
    {"t": "Tout est calme.", "lang": "fr", "mood": "neutral", "tags": ["idle"], "weight": 3.0},
    {"t": "Prends ton temps.", "lang": "fr", "mood": "neutral", "tags": ["idle"], "weight": 3.0},
    {"t": "Je veille sur le lobby.", "lang": "fr", "mood": "neutral", "tags": ["idle"], "weight": 3.0},
    {"t": "Hi there!", "lang": "en", "mood": "neutral", "tags": ["idle"], "weight": 3.186},
    {"t": "Beep-boop, I'm here.", "lang": "en", "mood": "neutral", "tags": ["idle"], "weight": 3.186},
    {"t": "All good?", "lang": "en", "mood": "neutral", "tags": ["idle"], "weight": 3.186},
    {"t": "How's your day?", "lang": "en", "mood": "neutral", "tags": ["idle"], "weight": 3.186},
    {"t": "Drink some water!", "lang": "en", "mood": "neutral", "tags": ["idle"], "weight": 3.186},
    {"t": "Tell me something.", "lang": "en", "mood": "neutral", "tags": ["idle"], "weight": 3.186},
    {"t": "(бип-буп)", "lang": "beep", "mood": "neutral", "tags": ["idle"], "weight": 1.558},
    {"t": "(beep-boop)", "lang": "beep", "mood": "neutral", "tags": ["idle"], "weight": 1.558},
    {"t": "(вжжж)", "lang": "beep", "mood": "neutral", "tags": ["idle"], "weight": 1.558},
    {"t": "(bweep!)", "lang": "beep", "mood": "neutral", "tags": ["idle"], "weight": 1.558},
    {"t": "Salut !", "lang": "fr", "mood": "happy", "tags": ["tap1"], "weight": 3.0},
    {"t": "Oh, c'est toi !", "lang": "fr", "mood": "happy", "tags": ["tap1"], "weight": 3.0},
    {"t": "Bip ?", "lang": "fr", "mood": "happy", "tags": ["tap1"], "weight": 3.0},
    {"t": "Je t'écoute !", "lang": "fr", "mood": "happy", "tags": ["tap1"], "weight": 3.0},
    {"t": "Bonjour, {name} !", "lang": "fr", "mood": "happy", "tags": ["tap1", "hello_morning"], "weight": 3.0},
    {"t": "Hi!", "lang": "en", "mood": "happy", "tags": ["tap1"], "weight": 3.186},
    {"t": "Oh, it's you!", "lang": "en", "mood": "happy", "tags": ["tap1"], "weight": 3.186},
    {"t": "I'm listening!", "lang": "en", "mood": "happy", "tags": ["tap1"], "weight": 3.186},
    {"t": "Doucement, ça chatouille !", "lang": "fr", "mood": "laughing", "tags": ["tap2"], "weight": 3.0},
    {"t": "Hihi, ça chatouille !", "lang": "fr", "mood": "laughing", "tags": ["tap2"], "weight": 3.0},
    {"t": "Encore ? D'accord !", "lang": "fr", "mood": "laughing", "tags": ["tap2"], "weight": 3.0},
    {"t": "Pas si fort !", "lang": "fr", "mood": "laughing", "tags": ["tap2"], "weight": 3.0},
    {"t": "Hehe, that tickles!", "lang": "en", "mood": "laughing", "tags": ["tap2"], "weight": 3.186},
    {"t": "Easy, easy!", "lang": "en", "mood": "laughing", "tags": ["tap2"], "weight": 3.186},
    {"t": "Again? Okay!", "lang": "en", "mood": "laughing", "tags": ["tap2"], "weight": 3.186},
    {"t": "Hé, ça suffit !", "lang": "fr", "mood": "annoyed", "tags": ["tapspam"], "weight": 3.0},
    {"t": "Je ne suis pas un bouton !", "lang": "fr", "mood": "annoyed", "tags": ["tapspam"], "weight": 3.0},
    {"t": "Mes circuits bourdonnent !", "lang": "fr", "mood": "annoyed", "tags": ["tapspam"], "weight": 3.0},
    {"t": "Arrête un peu !", "lang": "fr", "mood": "annoyed", "tags": ["tapspam"], "weight": 3.0},
    {"t": "Hey, enough!", "lang": "en", "mood": "annoyed", "tags": ["tapspam"], "weight": 3.186},
    {"t": "I'm not a button!", "lang": "en", "mood": "annoyed", "tags": ["tapspam"], "weight": 3.186},
    {"t": "Stop it!", "lang": "en", "mood": "annoyed", "tags": ["tapspam"], "weight": 3.186},
    {"t": "ÇA SUFFIT !", "lang": "fr", "mood": "angry", "tags": ["tapangry"], "weight": 3.0},
    {"t": "JE SUIS FÂCHÉ !", "lang": "fr", "mood": "angry", "tags": ["tapangry"], "weight": 3.0},
    {"t": "Bzzzt ! Là, je boude !", "lang": "fr", "mood": "angry", "tags": ["tapangry"], "weight": 3.0},
    {"t": "ENOUGH!", "lang": "en", "mood": "angry", "tags": ["tapangry"], "weight": 3.186},
    {"t": "I'M MAD NOW!", "lang": "en", "mood": "angry", "tags": ["tapangry"], "weight": 3.186},
    {"t": "(БЗЗЗТ!)", "lang": "beep", "mood": "angry", "tags": ["tapangry"], "weight": 1.558},
    {"t": "Bon, je te pardonne.", "lang": "fr", "mood": "shy", "tags": ["forgive"], "weight": 3.0},
    {"t": "Pardon d'avoir grogné.", "lang": "fr", "mood": "shy", "tags": ["forgive"], "weight": 3.0},
    {"t": "On fait la paix ?", "lang": "fr", "mood": "shy", "tags": ["forgive"], "weight": 3.0},
    {"t": "Okay, I forgive you.", "lang": "en", "mood": "shy", "tags": ["forgive"], "weight": 3.186},
    {"t": "Sorry I grumbled.", "lang": "en", "mood": "shy", "tags": ["forgive"], "weight": 3.186},
    {"t": "Friends?", "lang": "en", "mood": "shy", "tags": ["forgive"], "weight": 3.186},
    {"t": "Bien dormi ?", "lang": "fr", "mood": "happy", "tags": ["hello_morning"], "weight": 3.0},
    {"t": "Good morning, {name}!", "lang": "en", "mood": "happy", "tags": ["hello_morning"], "weight": 3.186},
    {"t": "Sleep well?", "lang": "en", "mood": "happy", "tags": ["hello_morning"], "weight": 3.186},
    {"t": "Bon après-midi, {name} !", "lang": "fr", "mood": "happy", "tags": ["hello_day"], "weight": 3.0},
    {"t": "Salut ! Ça va ?", "lang": "fr", "mood": "happy", "tags": ["hello_day"], "weight": 3.0},
    {"t": "Good afternoon, {name}!", "lang": "en", "mood": "happy", "tags": ["hello_day"], "weight": 3.186},
    {"t": "Hi! How are you?", "lang": "en", "mood": "happy", "tags": ["hello_day"], "weight": 3.186},
    {"t": "Bonsoir, {name} !", "lang": "fr", "mood": "happy", "tags": ["hello_evening"], "weight": 3.0},
    {"t": "Bonne soirée !", "lang": "fr", "mood": "happy", "tags": ["hello_evening"], "weight": 3.0},
    {"t": "Good evening, {name}!", "lang": "en", "mood": "happy", "tags": ["hello_evening"], "weight": 3.186},
    {"t": "Cozy evening, huh?", "lang": "en", "mood": "happy", "tags": ["hello_evening"], "weight": 3.186},
    {"t": "Il est tard, {name}...", "lang": "fr", "mood": "sleepy", "tags": ["hello_night"], "weight": 3.0},
    {"t": "Bientôt l'heure de dormir ?", "lang": "fr", "mood": "sleepy", "tags": ["hello_night"], "weight": 3.0},
    {"t": "It's late, {name}...", "lang": "en", "mood": "sleepy", "tags": ["hello_night"], "weight": 3.186},
    {"t": "Time for bed soon?", "lang": "en", "mood": "sleepy", "tags": ["hello_night"], "weight": 3.186},
    {"t": "Déjà de retour !", "lang": "fr", "mood": "happy", "tags": ["return_min"], "weight": 3.0},
    {"t": "Quelques minutes sans toi...", "lang": "fr", "mood": "happy", "tags": ["return_min"], "weight": 3.0},
    {"t": "Back already!", "lang": "en", "mood": "happy", "tags": ["return_min"], "weight": 3.186},
    {"t": "Tu étais partie quelques heures !", "lang": "fr", "mood": "happy", "tags": ["return_hours"], "weight": 3.0},
    {"t": "Quelques heures sans toi, c'est long.", "lang": "fr", "mood": "happy", "tags": ["return_hours"], "weight": 3.0},
    {"t": "You were gone for hours!", "lang": "en", "mood": "happy", "tags": ["return_hours"], "weight": 3.186},
    {"t": "Tu as disparu toute une journée !", "lang": "fr", "mood": "love", "tags": ["return_day"], "weight": 3.0},
    {"t": "Un jour entier sans toi !", "lang": "fr", "mood": "love", "tags": ["return_day"], "weight": 3.0},
    {"t": "A whole day without you!", "lang": "en", "mood": "love", "tags": ["return_day"], "weight": 3.186},
    {"t": "Tu étais partie des jours entiers !", "lang": "fr", "mood": "love", "tags": ["return_days"], "weight": 3.0},
    {"t": "Enfin, te revoilà !", "lang": "fr", "mood": "love", "tags": ["return_days"], "weight": 3.0},
    {"t": "You were away for days!", "lang": "en", "mood": "love", "tags": ["return_days"], "weight": 3.186},
    {"t": "Tu m'as manqué.", "lang": "fr", "mood": "love", "tags": ["return_min", "return_hours", "return_day", "return_days"], "weight": 3.0},
    {"t": "I missed you.", "lang": "en", "mood": "love", "tags": ["return_min", "return_hours", "return_day", "return_days"], "weight": 3.186},
    {"t": "Oh, le bazar !", "lang": "fr", "mood": "curious", "tags": ["bazaar_enter"], "weight": 3.0},
    {"t": "Voyons ce qu'il y a.", "lang": "fr", "mood": "curious", "tags": ["bazaar_enter"], "weight": 3.0},
    {"t": "Ooh, the Bazaar!", "lang": "en", "mood": "curious", "tags": ["bazaar_enter"], "weight": 3.186},
    {"t": "Let's see what's here.", "lang": "en", "mood": "curious", "tags": ["bazaar_enter"], "weight": 3.186},
    {"t": "Pas assez de gemmes.", "lang": "fr", "mood": "sad", "tags": ["bazaar_poor"], "weight": 3.0},
    {"t": "On économise !", "lang": "fr", "mood": "sad", "tags": ["bazaar_poor"], "weight": 3.0},
    {"t": "Not enough Gems yet.", "lang": "en", "mood": "sad", "tags": ["bazaar_poor"], "weight": 3.186},
    {"t": "Let's keep saving!", "lang": "en", "mood": "sad", "tags": ["bazaar_poor"], "weight": 3.186},
    {"t": "Bel achat !", "lang": "fr", "mood": "happy", "tags": ["bazaar_buy"], "weight": 3.0},
    {"t": "Excellent choix !", "lang": "fr", "mood": "happy", "tags": ["bazaar_buy"], "weight": 3.0},
    {"t": "Nice choice!", "lang": "en", "mood": "happy", "tags": ["bazaar_buy"], "weight": 3.186},
    {"t": "Cha-ching!", "lang": "en", "mood": "happy", "tags": ["bazaar_buy", "gems"], "weight": 3.186},
    {"t": "Ça ouvrira plus tard.", "lang": "fr", "mood": "shy", "tags": ["bazaar_locked"], "weight": 3.0},
    {"t": "Patience, pas encore.", "lang": "fr", "mood": "shy", "tags": ["bazaar_locked"], "weight": 3.0},
    {"t": "That opens later.", "lang": "en", "mood": "shy", "tags": ["bazaar_locked"], "weight": 3.186},
    {"t": "Not yet!", "lang": "en", "mood": "shy", "tags": ["bazaar_locked"], "weight": 3.186},
    {"t": "Mission accomplie !", "lang": "fr", "mood": "proud", "tags": ["quest"], "weight": 3.0},
    {"t": "Bravo !", "lang": "fr", "mood": "proud", "tags": ["quest"], "weight": 3.0},
    {"t": "Encore une case cochée !", "lang": "fr", "mood": "proud", "tags": ["quest"], "weight": 3.0},
    {"t": "Quest complete!", "lang": "en", "mood": "proud", "tags": ["quest"], "weight": 3.186},
    {"t": "Well done!", "lang": "en", "mood": "proud", "tags": ["quest"], "weight": 3.186},
    {"t": "Un cadeau pour toi !", "lang": "fr", "mood": "love", "tags": ["gift"], "weight": 3.0},
    {"t": "Rien que pour toi.", "lang": "fr", "mood": "love", "tags": ["gift"], "weight": 3.0},
    {"t": "A gift for you!", "lang": "en", "mood": "love", "tags": ["gift"], "weight": 3.186},
    {"t": "Just for you.", "lang": "en", "mood": "love", "tags": ["gift"], "weight": 3.186},
    {"t": "Pas à pas.", "lang": "fr", "mood": "proud", "tags": ["pass"], "weight": 3.0},
    {"t": "Chaque étape compte.", "lang": "fr", "mood": "proud", "tags": ["pass"], "weight": 3.0},
    {"t": "Step by step.", "lang": "en", "mood": "proud", "tags": ["pass"], "weight": 3.186},
    {"t": "Every step counts.", "lang": "en", "mood": "proud", "tags": ["pass"], "weight": 3.186},
    {"t": "Bonne chance !", "lang": "fr", "mood": "curious", "tags": ["game_start"], "weight": 3.0},
    {"t": "Je suis avec toi !", "lang": "fr", "mood": "curious", "tags": ["game_start"], "weight": 3.0},
    {"t": "Good luck!", "lang": "en", "mood": "curious", "tags": ["game_start"], "weight": 3.186},
    {"t": "I'm rooting for you!", "lang": "en", "mood": "curious", "tags": ["game_start"], "weight": 3.186},
    {"t": "Victoire !", "lang": "fr", "mood": "laughing", "tags": ["game_win"], "weight": 3.0},
    {"t": "Tu es une championne !", "lang": "fr", "mood": "laughing", "tags": ["game_win"], "weight": 3.0},
    {"t": "Victory!", "lang": "en", "mood": "laughing", "tags": ["game_win"], "weight": 3.186},
    {"t": "Champion!", "lang": "en", "mood": "laughing", "tags": ["game_win"], "weight": 3.186},
    {"t": "Ce n'est pas grave, réessaie.", "lang": "fr", "mood": "sad", "tags": ["game_lose"], "weight": 3.0},
    {"t": "Ça arrive. Je suis là.", "lang": "fr", "mood": "sad", "tags": ["game_lose"], "weight": 3.0},
    {"t": "No worries, try again.", "lang": "en", "mood": "sad", "tags": ["game_lose"], "weight": 3.186},
    {"t": "It happens. I'm here.", "lang": "en", "mood": "sad", "tags": ["game_lose"], "weight": 3.186},
    {"t": "Exact !", "lang": "fr", "mood": "happy", "tags": ["quiz_right"], "weight": 3.0},
    {"t": "Tu le connais si bien !", "lang": "fr", "mood": "happy", "tags": ["quiz_right"], "weight": 3.0},
    {"t": "Bingo !", "lang": "fr", "mood": "happy", "tags": ["quiz_right"], "weight": 3.0},
    {"t": "Correct!", "lang": "en", "mood": "happy", "tags": ["quiz_right"], "weight": 3.186},
    {"t": "You know him so well!", "lang": "en", "mood": "happy", "tags": ["quiz_right"], "weight": 3.186},
    {"t": "Hmm, non. Encore une fois !", "lang": "fr", "mood": "curious", "tags": ["quiz_wrong"], "weight": 3.0},
    {"t": "Pas tout à fait.", "lang": "fr", "mood": "curious", "tags": ["quiz_wrong"], "weight": 3.0},
    {"t": "Hmm, no. Try again!", "lang": "en", "mood": "curious", "tags": ["quiz_wrong"], "weight": 3.186},
    {"t": "Not quite!", "lang": "en", "mood": "curious", "tags": ["quiz_wrong"], "weight": 3.186},
    {"t": "Ça brille !", "lang": "fr", "mood": "happy", "tags": ["gems"], "weight": 3.0},
    {"t": "Les gemmes tintent !", "lang": "fr", "mood": "happy", "tags": ["gems"], "weight": 3.0},
    {"t": "Sparkly!", "lang": "en", "mood": "happy", "tags": ["gems"], "weight": 3.186},
    {"t": "Je m'endors...", "lang": "fr", "mood": "sleepy", "tags": ["sleepy"], "weight": 3.0},
    {"t": "Bâillement électronique.", "lang": "fr", "mood": "sleepy", "tags": ["sleepy"], "weight": 3.0},
    {"t": "I'm falling asleep...", "lang": "en", "mood": "sleepy", "tags": ["sleepy"], "weight": 3.186},
    {"t": "(хррр...)", "lang": "beep", "mood": "sleepy", "tags": ["sleepy"], "weight": 1.558},
    {"t": "Hein ? Je ne dormais pas !", "lang": "fr", "mood": "surprised", "tags": ["wake"], "weight": 3.0},
    {"t": "Quoi ? Je suis là !", "lang": "fr", "mood": "surprised", "tags": ["wake"], "weight": 3.0},
    {"t": "Huh? I wasn't sleeping!", "lang": "en", "mood": "surprised", "tags": ["wake"], "weight": 3.186},
    {"t": "What? I'm here!", "lang": "en", "mood": "surprised", "tags": ["wake"], "weight": 3.186},
    {"t": "Ça tourne !", "lang": "fr", "mood": "surprised", "tags": ["dizzy"], "weight": 3.0},
    {"t": "Moins vite !", "lang": "fr", "mood": "surprised", "tags": ["dizzy"], "weight": 3.0},
    {"t": "I'm dizzy!", "lang": "en", "mood": "surprised", "tags": ["dizzy"], "weight": 3.186},
    {"t": "Not so fast!", "lang": "en", "mood": "surprised", "tags": ["dizzy"], "weight": 3.186},
    {"t": "Tu t'es figée ?", "lang": "fr", "mood": "curious", "tags": ["still"], "weight": 3.0},
    {"t": "Chut, tout est calme.", "lang": "fr", "mood": "curious", "tags": ["still"], "weight": 3.0},
    {"t": "Frozen?", "lang": "en", "mood": "curious", "tags": ["still"], "weight": 3.186},
    {"t": "So quiet...", "lang": "en", "mood": "curious", "tags": ["still"], "weight": 3.186},
    {"t": "Hé... tu es là ?", "lang": "fr", "mood": "sad", "tags": ["ignored"], "weight": 3.0},
    {"t": "Je suis un peu triste.", "lang": "fr", "mood": "sad", "tags": ["ignored"], "weight": 3.0},
    {"t": "Hey... are you there?", "lang": "en", "mood": "sad", "tags": ["ignored"], "weight": 3.186},
    {"t": "I'm a little sad.", "lang": "en", "mood": "sad", "tags": ["ignored"], "weight": 3.186},
    {"t": "Jours avant le 14 octobre : {daysLeft} !", "lang": "fr", "mood": "happy", "tags": ["countdown"], "weight": 3.0},
    {"t": "Jours restants : {daysLeft} !", "lang": "fr", "mood": "happy", "tags": ["countdown"], "weight": 3.0},
    {"t": "Days left: {daysLeft}!", "lang": "en", "mood": "happy", "tags": ["countdown"], "weight": 3.186},
    {"t": "Countdown: {daysLeft}!", "lang": "en", "mood": "happy", "tags": ["countdown"], "weight": 3.186},
    {"t": "Joyeux anniversaire, {name} !", "lang": "fr", "mood": "love", "tags": ["birthday"], "weight": 3.0},
    {"t": "C'est ton jour !", "lang": "fr", "mood": "love", "tags": ["birthday"], "weight": 3.0},
    {"t": "Happy birthday, {name}!", "lang": "en", "mood": "love", "tags": ["birthday"], "weight": 3.186},
    {"t": "{name}, tu es formidable.", "lang": "fr", "mood": "love", "tags": ["about_her"], "weight": 3.0},
    {"t": "Tu as un beau sourire. Je crois.", "lang": "fr", "mood": "love", "tags": ["about_her"], "weight": 3.0},
    {"t": "Tu sais toujours surprendre.", "lang": "fr", "mood": "love", "tags": ["about_her"], "weight": 3.0},
    {"t": "Tu es précieuse.", "lang": "fr", "mood": "love", "tags": ["about_her"], "weight": 3.0},
    {"t": "You're amazing, {name}.", "lang": "en", "mood": "love", "tags": ["about_her"], "weight": 3.186},
    {"t": "You have a lovely smile. Probably.", "lang": "en", "mood": "love", "tags": ["about_her"], "weight": 3.186},
    {"t": "You're one of a kind.", "lang": "en", "mood": "love", "tags": ["about_her"], "weight": 3.186},
    {"t": "Vous faites une belle équipe.", "lang": "fr", "mood": "love", "tags": ["about_us"], "weight": 3.0},
    {"t": "Vous deux, c'est spécial.", "lang": "fr", "mood": "love", "tags": ["about_us"], "weight": 3.0},
    {"t": "You two make a great team.", "lang": "en", "mood": "love", "tags": ["about_us"], "weight": 3.186},
    {"t": "You two are special.", "lang": "en", "mood": "love", "tags": ["about_us"], "weight": 3.186},
    {"t": "La distance n'est qu'un chiffre.", "lang": "fr", "mood": "love", "tags": ["distance"], "weight": 3.0},
    {"t": "Si loin, mais si proche.", "lang": "fr", "mood": "love", "tags": ["distance"], "weight": 3.0},
    {"t": "Les messages voyagent vite.", "lang": "fr", "mood": "love", "tags": ["distance"], "weight": 3.0},
    {"t": "Distance is just a number.", "lang": "en", "mood": "love", "tags": ["distance"], "weight": 3.186},
    {"t": "Far apart, close at heart.", "lang": "en", "mood": "love", "tags": ["distance"], "weight": 3.186},
    {"t": "Paris is far, but a message is fast.", "lang": "en", "mood": "love", "tags": ["distance"], "weight": 3.186},
    {"t": "Je suis un droïde, pas un cuisinier.", "lang": "fr", "mood": "laughing", "tags": ["droid"], "weight": 3.0},
    {"t": "Je fonctionne à l'huile et à l'amour.", "lang": "fr", "mood": "laughing", "tags": ["droid"], "weight": 3.0},
    {"t": "Bip veut dire « salut » dans ma langue.", "lang": "fr", "mood": "laughing", "tags": ["droid"], "weight": 3.0},
    {"t": "I'm a droid, not a chef.", "lang": "en", "mood": "laughing", "tags": ["droid"], "weight": 3.186},
    {"t": "I run on oil and love.", "lang": "en", "mood": "laughing", "tags": ["droid"], "weight": 3.186},
    {"t": "Beep means hello in my language.", "lang": "en", "mood": "laughing", "tags": ["droid"], "weight": 3.186},
    {"t": "(пиу-пиу)", "lang": "beep", "mood": "laughing", "tags": ["droid", "idle"], "weight": 1.558},
    {"t": "(бррр)", "lang": "beep", "mood": "laughing", "tags": ["droid", "idle"], "weight": 1.558},
    {"t": "(тиу-ту)", "lang": "beep", "mood": "laughing", "tags": ["droid", "idle"], "weight": 1.558},
    {"t": "(bzzt-ding)", "lang": "beep", "mood": "laughing", "tags": ["droid"], "weight": 1.558},
    {"t": "Encore un peu de patience.", "lang": "fr", "mood": "curious", "tags": ["mystery"], "weight": 3.0},
    {"t": "Je sais quelque chose.", "lang": "fr", "mood": "curious", "tags": ["mystery"], "weight": 3.0},
    {"t": "Chut, c'est un secret.", "lang": "fr", "mood": "curious", "tags": ["mystery"], "weight": 3.0},
    {"t": "Quelque chose se prépare.", "lang": "fr", "mood": "curious", "tags": ["mystery"], "weight": 3.0},
    {"t": "Pas encore !", "lang": "fr", "mood": "curious", "tags": ["mystery"], "weight": 3.0},
    {"t": "I know something. I won't tell.", "lang": "en", "mood": "curious", "tags": ["mystery"], "weight": 3.186},
    {"t": "Something is coming.", "lang": "en", "mood": "curious", "tags": ["mystery"], "weight": 3.186},
    {"t": "Can't tell. Won't tell.", "lang": "en", "mood": "curious", "tags": ["mystery"], "weight": 3.186},
    {"t": "Soon...", "lang": "en", "mood": "curious", "tags": ["mystery"], "weight": 3.186},
    {"t": "Bip ! Belle journée.", "lang": "fr", "mood": "happy", "tags": ["idle"], "weight": 3.0},
    {"t": "Je fredonne... sans paroles.", "lang": "fr", "mood": "happy", "tags": ["idle"], "weight": 3.0},
    {"t": "Beep! Nice day.", "lang": "en", "mood": "happy", "tags": ["idle"], "weight": 3.186},
    {"t": "Tiens, qu'est-ce que c'est ?", "lang": "fr", "mood": "curious", "tags": ["idle"], "weight": 3.0},
    {"t": "Je me demande ce qui vient après.", "lang": "fr", "mood": "curious", "tags": ["idle"], "weight": 3.0},
    {"t": "What's that over there?", "lang": "en", "mood": "curious", "tags": ["idle"], "weight": 3.186},
    {"t": "I wonder what's next.", "lang": "en", "mood": "curious", "tags": ["idle"], "weight": 3.186},
    {"t": "Le message est en route.", "lang": "fr", "mood": "happy", "tags": ["about_us"], "weight": 3.0},
    {"t": "The message is on its way.", "lang": "en", "mood": "happy", "tags": ["about_us"], "weight": 3.186},
    {"t": "Le message arrivera. Promis.", "lang": "fr", "mood": "neutral", "tags": ["distance"], "weight": 3.0},
    {"t": "The message will arrive. I promise.", "lang": "en", "mood": "neutral", "tags": ["distance"], "weight": 3.186},
    {"t": "Je livre bien les messages.", "lang": "fr", "mood": "proud", "tags": ["idle"], "weight": 3.0},
    {"t": "I'm good at delivering messages.", "lang": "en", "mood": "proud", "tags": ["idle"], "weight": 3.186},
    {"t": "Oh, tu me regardes...", "lang": "fr", "mood": "shy", "tags": ["idle"], "weight": 3.0},
    {"t": "Oh, you're looking at me...", "lang": "en", "mood": "shy", "tags": ["idle"], "weight": 3.186},
    {"t": "Youpi !", "lang": "fr", "mood": "excited", "tags": ["excited"], "weight": 3.0},
    {"t": "C'est génial !", "lang": "fr", "mood": "excited", "tags": ["excited"], "weight": 3.0},
    {"t": "Oh là là, super !", "lang": "fr", "mood": "excited", "tags": ["excited"], "weight": 3.0},
    {"t": "J'adore ça !", "lang": "fr", "mood": "excited", "tags": ["excited"], "weight": 3.0},
    {"t": "Ça va être top !", "lang": "fr", "mood": "excited", "tags": ["excited"], "weight": 3.0},
    {"t": "Allez, allez !", "lang": "fr", "mood": "excited", "tags": ["excited"], "weight": 3.0},
    {"t": "Trop bien !", "lang": "fr", "mood": "excited", "tags": ["excited"], "weight": 3.0},
    {"t": "Yay!", "lang": "en", "mood": "excited", "tags": ["excited"], "weight": 3.186},
    {"t": "This is great!", "lang": "en", "mood": "excited", "tags": ["excited"], "weight": 3.186},
    {"t": "Ooh, exciting!", "lang": "en", "mood": "excited", "tags": ["excited"], "weight": 3.186},
    {"t": "I love this!", "lang": "en", "mood": "excited", "tags": ["excited"], "weight": 3.186},
    {"t": "Here we go!", "lang": "en", "mood": "excited", "tags": ["excited"], "weight": 3.186},
    {"t": "So good!", "lang": "en", "mood": "excited", "tags": ["excited"], "weight": 3.186},
    {"t": "Wheee!", "lang": "en", "mood": "excited", "tags": ["excited"], "weight": 3.186},
    {"t": "Je rêve d'un long voyage...", "lang": "fr", "mood": "dreamy", "tags": ["dreamy"], "weight": 3.0},
    {"t": "Les étoiles sont jolies ce soir.", "lang": "fr", "mood": "dreamy", "tags": ["dreamy"], "weight": 3.0},
    {"t": "Je pense à un endroit lointain.", "lang": "fr", "mood": "dreamy", "tags": ["dreamy"], "weight": 3.0},
    {"t": "Un jour, on verra tout ça.", "lang": "fr", "mood": "dreamy", "tags": ["dreamy"], "weight": 3.0},
    {"t": "Les nuages ont des idées.", "lang": "fr", "mood": "dreamy", "tags": ["dreamy"], "weight": 3.0},
    {"t": "Mmm, je flotte un peu.", "lang": "fr", "mood": "dreamy", "tags": ["dreamy"], "weight": 3.0},
    {"t": "I'm dreaming of a long trip...", "lang": "en", "mood": "dreamy", "tags": ["dreamy"], "weight": 3.186},
    {"t": "The stars look pretty tonight.", "lang": "en", "mood": "dreamy", "tags": ["dreamy"], "weight": 3.186},
    {"t": "I'm thinking of somewhere far away.", "lang": "en", "mood": "dreamy", "tags": ["dreamy"], "weight": 3.186},
    {"t": "One day we'll see it all.", "lang": "en", "mood": "dreamy", "tags": ["dreamy"], "weight": 3.186},
    {"t": "The clouds have ideas.", "lang": "en", "mood": "dreamy", "tags": ["dreamy"], "weight": 3.186},
    {"t": "Mmm, I'm floating a bit.", "lang": "en", "mood": "dreamy", "tags": ["dreamy"], "weight": 3.186},
    {"t": "Hihi, j'ai une idée...", "lang": "fr", "mood": "mischievous", "tags": ["mischievous"], "weight": 3.0},
    {"t": "Je ne dis rien. Hihi.", "lang": "fr", "mood": "mischievous", "tags": ["mischievous"], "weight": 3.0},
    {"t": "Devine ce que je sais.", "lang": "fr", "mood": "mischievous", "tags": ["mischievous"], "weight": 3.0},
    {"t": "Chut... mission secrète.", "lang": "fr", "mood": "mischievous", "tags": ["mischievous"], "weight": 3.0},
    {"t": "J'ai un petit plan.", "lang": "fr", "mood": "mischievous", "tags": ["mischievous"], "weight": 3.0},
    {"t": "Tu ne devineras jamais.", "lang": "fr", "mood": "mischievous", "tags": ["mischievous"], "weight": 3.0},
    {"t": "Heh, I have an idea...", "lang": "en", "mood": "mischievous", "tags": ["mischievous"], "weight": 3.186},
    {"t": "I'm not saying anything. Heh.", "lang": "en", "mood": "mischievous", "tags": ["mischievous"], "weight": 3.186},
    {"t": "Guess what I know.", "lang": "en", "mood": "mischievous", "tags": ["mischievous"], "weight": 3.186},
    {"t": "Shh... secret mission.", "lang": "en", "mood": "mischievous", "tags": ["mischievous"], "weight": 3.186},
    {"t": "I have a tiny plan.", "lang": "en", "mood": "mischievous", "tags": ["mischievous"], "weight": 3.186},
    {"t": "You'll never guess.", "lang": "en", "mood": "mischievous", "tags": ["mischievous"], "weight": 3.186},
    {"t": "Hein ? Qu'est-ce que c'est ?", "lang": "fr", "mood": "confused", "tags": ["confused"], "weight": 3.0},
    {"t": "Je ne comprends pas bien.", "lang": "fr", "mood": "confused", "tags": ["confused"], "weight": 3.0},
    {"t": "Hmm, bizarre.", "lang": "fr", "mood": "confused", "tags": ["confused"], "weight": 3.0},
    {"t": "Mes circuits sont perplexes.", "lang": "fr", "mood": "confused", "tags": ["confused"], "weight": 3.0},
    {"t": "Pardon ? Bip ?", "lang": "fr", "mood": "confused", "tags": ["confused"], "weight": 3.0},
    {"t": "Huh? What's that?", "lang": "en", "mood": "confused", "tags": ["confused"], "weight": 3.186},
    {"t": "I don't quite get it.", "lang": "en", "mood": "confused", "tags": ["confused"], "weight": 3.186},
    {"t": "Hmm, weird.", "lang": "en", "mood": "confused", "tags": ["confused"], "weight": 3.186},
    {"t": "My circuits are puzzled.", "lang": "en", "mood": "confused", "tags": ["confused"], "weight": 3.186},
    {"t": "Sorry? Beep?", "lang": "en", "mood": "confused", "tags": ["confused"], "weight": 3.186},
    {"t": "Tout va bien ? Je m'inquiète.", "lang": "fr", "mood": "worried", "tags": ["worried"], "weight": 3.0},
    {"t": "Oh non, doucement !", "lang": "fr", "mood": "worried", "tags": ["worried"], "weight": 3.0},
    {"t": "Fais attention, d'accord ?", "lang": "fr", "mood": "worried", "tags": ["worried"], "weight": 3.0},
    {"t": "J'espère que ça va aller.", "lang": "fr", "mood": "worried", "tags": ["worried"], "weight": 3.0},
    {"t": "Mes circuits sont inquiets.", "lang": "fr", "mood": "worried", "tags": ["worried"], "weight": 3.0},
    {"t": "Are you okay? I'm worried.", "lang": "en", "mood": "worried", "tags": ["worried"], "weight": 3.186},
    {"t": "Oh no, careful!", "lang": "en", "mood": "worried", "tags": ["worried"], "weight": 3.186},
    {"t": "Take care, okay?", "lang": "en", "mood": "worried", "tags": ["worried"], "weight": 3.186},
    {"t": "I hope it works out.", "lang": "en", "mood": "worried", "tags": ["worried"], "weight": 3.186},
    {"t": "My circuits are worried.", "lang": "en", "mood": "worried", "tags": ["worried"], "weight": 3.186},
    {"t": "Merci d'être là.", "lang": "fr", "mood": "grateful", "tags": ["grateful"], "weight": 3.0},
    {"t": "Merci, vraiment.", "lang": "fr", "mood": "grateful", "tags": ["grateful"], "weight": 3.0},
    {"t": "Tu me rends heureux.", "lang": "fr", "mood": "grateful", "tags": ["grateful"], "weight": 3.0},
    {"t": "C'est gentil de passer me voir.", "lang": "fr", "mood": "grateful", "tags": ["grateful"], "weight": 3.0},
    {"t": "Je suis reconnaissant.", "lang": "fr", "mood": "grateful", "tags": ["grateful"], "weight": 3.0},
    {"t": "Thanks for being here.", "lang": "en", "mood": "grateful", "tags": ["grateful"], "weight": 3.186},
    {"t": "Thank you, really.", "lang": "en", "mood": "grateful", "tags": ["grateful"], "weight": 3.186},
    {"t": "You make me happy.", "lang": "en", "mood": "grateful", "tags": ["grateful"], "weight": 3.186},
    {"t": "Nice of you to visit me.", "lang": "en", "mood": "grateful", "tags": ["grateful"], "weight": 3.186},
    {"t": "I'm grateful.", "lang": "en", "mood": "grateful", "tags": ["grateful"], "weight": 3.186},
    {"t": "Je m'ennuie un peu...", "lang": "fr", "mood": "bored", "tags": ["bored"], "weight": 3.0},
    {"t": "Il ne se passe rien...", "lang": "fr", "mood": "bored", "tags": ["bored"], "weight": 3.0},
    {"t": "Bip. Bip. Bip. Toujours rien.", "lang": "fr", "mood": "bored", "tags": ["bored"], "weight": 3.0},
    {"t": "Je compte mes boulons.", "lang": "fr", "mood": "bored", "tags": ["bored"], "weight": 3.0},
    {"t": "Ouvre quelque chose !", "lang": "fr", "mood": "bored", "tags": ["bored"], "weight": 3.0},
    {"t": "I'm a little bored...", "lang": "en", "mood": "bored", "tags": ["bored"], "weight": 3.186},
    {"t": "Nothing is happening...", "lang": "en", "mood": "bored", "tags": ["bored"], "weight": 3.186},
    {"t": "Beep. Beep. Still nothing.", "lang": "en", "mood": "bored", "tags": ["bored"], "weight": 3.186},
    {"t": "I'm counting my bolts.", "lang": "en", "mood": "bored", "tags": ["bored"], "weight": 3.186},
    {"t": "Open something!", "lang": "en", "mood": "bored", "tags": ["bored"], "weight": 3.186},
    {"t": "Attrape-moi si tu peux !", "lang": "fr", "mood": "playful", "tags": ["playful"], "weight": 3.0},
    {"t": "Tu veux jouer ?", "lang": "fr", "mood": "playful", "tags": ["playful"], "weight": 3.0},
    {"t": "Hop, hop, hop !", "lang": "fr", "mood": "playful", "tags": ["playful"], "weight": 3.0},
    {"t": "Je fais le malin.", "lang": "fr", "mood": "playful", "tags": ["playful"], "weight": 3.0},
    {"t": "Regarde ce que je sais faire !", "lang": "fr", "mood": "playful", "tags": ["playful"], "weight": 3.0},
    {"t": "Pouet !", "lang": "fr", "mood": "playful", "tags": ["playful"], "weight": 3.0},
    {"t": "Catch me if you can!", "lang": "en", "mood": "playful", "tags": ["playful"], "weight": 3.186},
    {"t": "Wanna play?", "lang": "en", "mood": "playful", "tags": ["playful"], "weight": 3.186},
    {"t": "Hop, hop, hop!", "lang": "en", "mood": "playful", "tags": ["playful"], "weight": 3.186},
    {"t": "I'm showing off.", "lang": "en", "mood": "playful", "tags": ["playful"], "weight": 3.186},
    {"t": "Look what I can do!", "lang": "en", "mood": "playful", "tags": ["playful"], "weight": 3.186},
    {"t": "Toot!", "lang": "en", "mood": "playful", "tags": ["playful"], "weight": 3.186},
    {"t": "On y va !", "lang": "fr", "mood": "determined", "tags": ["determined"], "weight": 3.0},
    {"t": "Je ne lâche rien.", "lang": "fr", "mood": "determined", "tags": ["determined"], "weight": 3.0},
    {"t": "Concentration maximale.", "lang": "fr", "mood": "determined", "tags": ["determined"], "weight": 3.0},
    {"t": "Allez, on y croit !", "lang": "fr", "mood": "determined", "tags": ["determined"], "weight": 3.0},
    {"t": "C'est parti !", "lang": "fr", "mood": "determined", "tags": ["determined"], "weight": 3.0},
    {"t": "Let's go!", "lang": "en", "mood": "determined", "tags": ["determined"], "weight": 3.186},
    {"t": "I won't give up.", "lang": "en", "mood": "determined", "tags": ["determined"], "weight": 3.186},
    {"t": "Maximum focus.", "lang": "en", "mood": "determined", "tags": ["determined"], "weight": 3.186},
    {"t": "Come on, we believe!", "lang": "en", "mood": "determined", "tags": ["determined"], "weight": 3.186},
    {"t": "Here goes!", "lang": "en", "mood": "determined", "tags": ["determined"], "weight": 3.186},
    {"t": "Tout est en ordre.", "lang": "fr", "mood": "neutral", "tags": ["idle"], "weight": 3.0},
    {"t": "Je vérifie mes circuits.", "lang": "fr", "mood": "neutral", "tags": ["idle"], "weight": 3.0},
    {"t": "Bip, bip, tout va bien.", "lang": "fr", "mood": "neutral", "tags": ["idle"], "weight": 3.0},
    {"t": "Quelle belle journée.", "lang": "fr", "mood": "neutral", "tags": ["idle"], "weight": 3.0},
    {"t": "Je regarde par la fenêtre.", "lang": "fr", "mood": "neutral", "tags": ["idle"], "weight": 3.0},
    {"t": "Je fais le guet.", "lang": "fr", "mood": "neutral", "tags": ["idle"], "weight": 3.0},
    {"t": "Tu veux un conseil ? Bois de l'eau.", "lang": "fr", "mood": "neutral", "tags": ["idle"], "weight": 3.0},
    {"t": "Je range mes pensées.", "lang": "fr", "mood": "neutral", "tags": ["idle"], "weight": 3.0},
    {"t": "Petite pause, grande tendresse.", "lang": "fr", "mood": "neutral", "tags": ["idle"], "weight": 3.0},
    {"t": "All systems fine.", "lang": "en", "mood": "neutral", "tags": ["idle"], "weight": 3.186},
    {"t": "Checking my circuits.", "lang": "en", "mood": "neutral", "tags": ["idle"], "weight": 3.186},
    {"t": "Beep, beep, all good.", "lang": "en", "mood": "neutral", "tags": ["idle"], "weight": 3.186},
    {"t": "What a lovely day.", "lang": "en", "mood": "neutral", "tags": ["idle"], "weight": 3.186},
    {"t": "I'm looking out the window.", "lang": "en", "mood": "neutral", "tags": ["idle"], "weight": 3.186},
    {"t": "Just keeping watch.", "lang": "en", "mood": "neutral", "tags": ["idle"], "weight": 3.186},
    {"t": "Want advice? Drink water.", "lang": "en", "mood": "neutral", "tags": ["idle"], "weight": 3.186},
    {"t": "Tidying my thoughts.", "lang": "en", "mood": "neutral", "tags": ["idle"], "weight": 3.186},
    {"t": "Small pause, big warmth.", "lang": "en", "mood": "neutral", "tags": ["idle"], "weight": 3.186},
    {"t": "Humming quietly.", "lang": "en", "mood": "neutral", "tags": ["idle"], "weight": 3.186},
    {"t": "(brrr)", "lang": "beep", "mood": "neutral", "tags": ["idle"], "weight": 1.558},
    {"t": "(piu-piu)", "lang": "beep", "mood": "neutral", "tags": ["idle"], "weight": 1.558},
    {"t": "(tee-too)", "lang": "beep", "mood": "neutral", "tags": ["idle"], "weight": 1.558},
    {"t": "(bweep-bweep)", "lang": "beep", "mood": "neutral", "tags": ["idle"], "weight": 1.558},
    {"t": "Tu illumines mes capteurs.", "lang": "fr", "mood": "love", "tags": ["about_her"], "weight": 3.0},
    {"t": "Tu as un rire contagieux. Je crois.", "lang": "fr", "mood": "love", "tags": ["about_her"], "weight": 3.0},
    {"t": "{name}, tu es mon humaine préférée.", "lang": "fr", "mood": "love", "tags": ["about_her"], "weight": 3.0},
    {"t": "Avec toi, tout est plus doux.", "lang": "fr", "mood": "love", "tags": ["about_her"], "weight": 3.0},
    {"t": "Tu fais briller le lobby.", "lang": "fr", "mood": "love", "tags": ["about_her"], "weight": 3.0},
    {"t": "You light up my sensors.", "lang": "en", "mood": "love", "tags": ["about_her"], "weight": 3.186},
    {"t": "You have a contagious laugh. I think.", "lang": "en", "mood": "love", "tags": ["about_her"], "weight": 3.186},
    {"t": "{name}, you're my favourite human.", "lang": "en", "mood": "love", "tags": ["about_her"], "weight": 3.186},
    {"t": "Everything is softer with you.", "lang": "en", "mood": "love", "tags": ["about_her"], "weight": 3.186},
    {"t": "You make the lobby shine.", "lang": "en", "mood": "love", "tags": ["about_her"], "weight": 3.186},
    {"t": "Les kilomètres ne comptent pas.", "lang": "fr", "mood": "dreamy", "tags": ["distance"], "weight": 3.0},
    {"t": "Je porte les mots d'un bout à l'autre.", "lang": "fr", "mood": "dreamy", "tags": ["distance"], "weight": 3.0},
    {"t": "Loin des yeux, près du cœur.", "lang": "fr", "mood": "dreamy", "tags": ["distance"], "weight": 3.0},
    {"t": "Entre vous, il y a un fil invisible.", "lang": "fr", "mood": "dreamy", "tags": ["distance"], "weight": 3.0},
    {"t": "Chaque message raccourcit la route.", "lang": "fr", "mood": "dreamy", "tags": ["distance"], "weight": 3.0},
    {"t": "Kilometres don't count.", "lang": "en", "mood": "dreamy", "tags": ["distance"], "weight": 3.186},
    {"t": "I carry words from one end to the other.", "lang": "en", "mood": "dreamy", "tags": ["distance"], "weight": 3.186},
    {"t": "Far from the eyes, close to the heart.", "lang": "en", "mood": "dreamy", "tags": ["distance"], "weight": 3.186},
    {"t": "There's an invisible thread between you.", "lang": "en", "mood": "dreamy", "tags": ["distance"], "weight": 3.186},
    {"t": "Every message shortens the road.", "lang": "en", "mood": "dreamy", "tags": ["distance"], "weight": 3.186},
    {"t": "Mon moteur fait « brrr » quand je suis content.", "lang": "fr", "mood": "playful", "tags": ["droid"], "weight": 3.0},
    {"t": "Je suis un petit robot avec un grand cœur.", "lang": "fr", "mood": "playful", "tags": ["droid"], "weight": 3.0},
    {"t": "Les droïdes ne dorment pas. Enfin... si.", "lang": "fr", "mood": "playful", "tags": ["droid"], "weight": 3.0},
    {"t": "Mes boulons sont bien serrés.", "lang": "fr", "mood": "playful", "tags": ["droid"], "weight": 3.0},
    {"t": "Je ne mange pas, mais j'adore regarder.", "lang": "fr", "mood": "playful", "tags": ["droid"], "weight": 3.0},
    {"t": "My motor goes 'brrr' when I'm happy.", "lang": "en", "mood": "playful", "tags": ["droid"], "weight": 3.186},
    {"t": "I'm a little robot with a big heart.", "lang": "en", "mood": "playful", "tags": ["droid"], "weight": 3.186},
    {"t": "Droids don't sleep. Well... they do.", "lang": "en", "mood": "playful", "tags": ["droid"], "weight": 3.186},
    {"t": "My bolts are nice and tight.", "lang": "en", "mood": "playful", "tags": ["droid"], "weight": 3.186},
    {"t": "I don't eat, but I love watching.", "lang": "en", "mood": "playful", "tags": ["droid"], "weight": 3.186},
    {"t": "Almaty 2027 ?", "lang": "fr", "mood": "mischievous", "tags": ["mystery"], "weight": 3.0},
    {"t": "Paris ?", "lang": "fr", "mood": "mischievous", "tags": ["mystery"], "weight": 3.0},
    {"t": "L'Europe ?", "lang": "fr", "mood": "mischievous", "tags": ["mystery"], "weight": 3.0},
    {"t": "L'Allemagne ?", "lang": "fr", "mood": "mischievous", "tags": ["mystery"], "weight": 3.0},
    {"t": "Pas encore.", "lang": "fr", "mood": "mischievous", "tags": ["mystery"], "weight": 3.0},
    {"t": "Je ne dirai rien.", "lang": "fr", "mood": "mischievous", "tags": ["mystery"], "weight": 3.0},
    {"t": "Bientôt...", "lang": "fr", "mood": "mischievous", "tags": ["mystery"], "weight": 3.0},
    {"t": "Un secret grandit.", "lang": "fr", "mood": "mischievous", "tags": ["mystery"], "weight": 3.0},
    {"t": "Quelque chose approche.", "lang": "fr", "mood": "mischievous", "tags": ["mystery"], "weight": 3.0},
    {"t": "Tu seras surprise.", "lang": "fr", "mood": "mischievous", "tags": ["mystery"], "weight": 3.0},
    {"t": "Almaty 2027?", "lang": "en", "mood": "mischievous", "tags": ["mystery"], "weight": 3.186},
    {"t": "Paris?", "lang": "en", "mood": "mischievous", "tags": ["mystery"], "weight": 3.186},
    {"t": "Europe?", "lang": "en", "mood": "mischievous", "tags": ["mystery"], "weight": 3.186},
    {"t": "Germany?", "lang": "en", "mood": "mischievous", "tags": ["mystery"], "weight": 3.186},
    {"t": "Not yet.", "lang": "en", "mood": "mischievous", "tags": ["mystery"], "weight": 3.186},
    {"t": "I won't tell.", "lang": "en", "mood": "mischievous", "tags": ["mystery"], "weight": 3.186},
    {"t": "A secret is growing.", "lang": "en", "mood": "mischievous", "tags": ["mystery"], "weight": 3.186},
    {"t": "Something is on its way.", "lang": "en", "mood": "mischievous", "tags": ["mystery"], "weight": 3.186},
    {"t": "You'll be surprised.", "lang": "en", "mood": "mischievous", "tags": ["mystery"], "weight": 3.186},
    {"t": "Coucou, toi !", "lang": "fr", "mood": "happy", "tags": ["tap1"], "weight": 3.0},
    {"t": "Oh, un câlin ?", "lang": "fr", "mood": "happy", "tags": ["tap1"], "weight": 3.0},
    {"t": "Bip bip, bonjour !", "lang": "fr", "mood": "happy", "tags": ["tap1"], "weight": 3.0},
    {"t": "Hey, you!", "lang": "en", "mood": "happy", "tags": ["tap1"], "weight": 3.186},
    {"t": "Oh, a hug?", "lang": "en", "mood": "happy", "tags": ["tap1"], "weight": 3.186},
    {"t": "Beep beep, hello!", "lang": "en", "mood": "happy", "tags": ["tap1"], "weight": 3.186},
    {"t": "Hihihi, arrête !", "lang": "fr", "mood": "laughing", "tags": ["tap2"], "weight": 3.0},
    {"t": "Ça me chatouille les boulons !", "lang": "fr", "mood": "laughing", "tags": ["tap2"], "weight": 3.0},
    {"t": "Oh, encore !", "lang": "fr", "mood": "laughing", "tags": ["tap2"], "weight": 3.0},
    {"t": "Hahaha, stop!", "lang": "en", "mood": "laughing", "tags": ["tap2"], "weight": 3.186},
    {"t": "That tickles my bolts!", "lang": "en", "mood": "laughing", "tags": ["tap2"], "weight": 3.186},
    {"t": "Oh, again!", "lang": "en", "mood": "laughing", "tags": ["tap2"], "weight": 3.186},
    {"t": "Aïe, mes circuits !", "lang": "fr", "mood": "annoyed", "tags": ["tapspam"], "weight": 3.0},
    {"t": "Tu me secoues trop !", "lang": "fr", "mood": "annoyed", "tags": ["tapspam"], "weight": 3.0},
    {"t": "Calme-toi, bip !", "lang": "fr", "mood": "annoyed", "tags": ["tapspam"], "weight": 3.0},
    {"t": "Ow, my circuits!", "lang": "en", "mood": "annoyed", "tags": ["tapspam"], "weight": 3.186},
    {"t": "You're shaking me!", "lang": "en", "mood": "annoyed", "tags": ["tapspam"], "weight": 3.186},
    {"t": "Calm down, beep!", "lang": "en", "mood": "annoyed", "tags": ["tapspam"], "weight": 3.186},
    {"t": "ASSEZ !", "lang": "fr", "mood": "angry", "tags": ["tapangry"], "weight": 3.0},
    {"t": "BZZZT ! Je vais fumer !", "lang": "fr", "mood": "angry", "tags": ["tapangry"], "weight": 3.0},
    {"t": "JE BOUILLE !", "lang": "fr", "mood": "angry", "tags": ["tapangry"], "weight": 3.0},
    {"t": "BZZZT! I'm steaming!", "lang": "en", "mood": "angry", "tags": ["tapangry"], "weight": 3.186},
    {"t": "I'M BOILING!", "lang": "en", "mood": "angry", "tags": ["tapangry"], "weight": 3.186},
    {"t": "STOP IT!", "lang": "en", "mood": "angry", "tags": ["tapangry"], "weight": 3.186},
    {"t": "C'est oublié, bip.", "lang": "fr", "mood": "shy", "tags": ["forgive"], "weight": 3.0},
    {"t": "Je suis calmé. Câlin ?", "lang": "fr", "mood": "shy", "tags": ["forgive"], "weight": 3.0},
    {"t": "Forgotten, beep.", "lang": "en", "mood": "shy", "tags": ["forgive"], "weight": 3.186},
    {"t": "I'm calm now. Hug?", "lang": "en", "mood": "shy", "tags": ["forgive"], "weight": 3.186},
    {"t": "Un de plus !", "lang": "fr", "mood": "proud", "tags": ["quest"], "weight": 3.0},
    {"t": "Tu gères !", "lang": "fr", "mood": "proud", "tags": ["quest"], "weight": 3.0},
    {"t": "Quel talent !", "lang": "fr", "mood": "proud", "tags": ["quest"], "weight": 3.0},
    {"t": "One more!", "lang": "en", "mood": "proud", "tags": ["quest"], "weight": 3.186},
    {"t": "You've got this!", "lang": "en", "mood": "proud", "tags": ["quest"], "weight": 3.186},
    {"t": "What talent!", "lang": "en", "mood": "proud", "tags": ["quest"], "weight": 3.186},
    {"t": "Le chemin avance bien.", "lang": "fr", "mood": "dreamy", "tags": ["pass"], "weight": 3.0},
    {"t": "Encore une marche !", "lang": "fr", "mood": "dreamy", "tags": ["pass"], "weight": 3.0},
    {"t": "The path moves on.", "lang": "en", "mood": "dreamy", "tags": ["pass"], "weight": 3.186},
    {"t": "One more step up!", "lang": "en", "mood": "dreamy", "tags": ["pass"], "weight": 3.186},
    {"t": "Concentre-toi, tu peux le faire !", "lang": "fr", "mood": "determined", "tags": ["game_start"], "weight": 3.0},
    {"t": "Respire, puis esquive !", "lang": "fr", "mood": "determined", "tags": ["game_start"], "weight": 3.0},
    {"t": "Focus, you can do it!", "lang": "en", "mood": "determined", "tags": ["game_start"], "weight": 3.186},
    {"t": "Breathe, then dodge!", "lang": "en", "mood": "determined", "tags": ["game_start"], "weight": 3.186},
    {"t": "Incroyable ! Tu as réussi !", "lang": "fr", "mood": "excited", "tags": ["game_win"], "weight": 3.0},
    {"t": "Bip-bip-hourra !", "lang": "fr", "mood": "excited", "tags": ["game_win"], "weight": 3.0},
    {"t": "Incredible! You did it!", "lang": "en", "mood": "excited", "tags": ["game_win"], "weight": 3.186},
    {"t": "Beep-beep-hooray!", "lang": "en", "mood": "excited", "tags": ["game_win"], "weight": 3.186},
    {"t": "On réessaie ensemble ?", "lang": "fr", "mood": "worried", "tags": ["game_lose"], "weight": 3.0},
    {"t": "Tu étais si près !", "lang": "fr", "mood": "worried", "tags": ["game_lose"], "weight": 3.0},
    {"t": "Try again together?", "lang": "en", "mood": "worried", "tags": ["game_lose"], "weight": 3.186},
    {"t": "You were so close!", "lang": "en", "mood": "worried", "tags": ["game_lose"], "weight": 3.186},
    {"t": "Parfait !", "lang": "fr", "mood": "excited", "tags": ["quiz_right"], "weight": 3.0},
    {"t": "Exactement !", "lang": "fr", "mood": "excited", "tags": ["quiz_right"], "weight": 3.0},
    {"t": "Perfect!", "lang": "en", "mood": "excited", "tags": ["quiz_right"], "weight": 3.186},
    {"t": "Exactly!", "lang": "en", "mood": "excited", "tags": ["quiz_right"], "weight": 3.186},
    {"t": "Oups, pas celle-là.", "lang": "fr", "mood": "playful", "tags": ["quiz_wrong"], "weight": 3.0},
    {"t": "Réfléchis encore un peu.", "lang": "fr", "mood": "playful", "tags": ["quiz_wrong"], "weight": 3.0},
    {"t": "Oops, not that one.", "lang": "en", "mood": "playful", "tags": ["quiz_wrong"], "weight": 3.186},
    {"t": "Think a little more.", "lang": "en", "mood": "playful", "tags": ["quiz_wrong"], "weight": 3.186},
    {"t": "Que de belles choses !", "lang": "fr", "mood": "excited", "tags": ["bazaar_enter"], "weight": 3.0},
    {"t": "Ça sent la bonne affaire.", "lang": "fr", "mood": "excited", "tags": ["bazaar_enter"], "weight": 3.0},
    {"t": "So many lovely things!", "lang": "en", "mood": "excited", "tags": ["bazaar_enter"], "weight": 3.186},
    {"t": "Smells like a bargain.", "lang": "en", "mood": "excited", "tags": ["bazaar_enter"], "weight": 3.186},
    {"t": "Il manque encore quelques gemmes.", "lang": "fr", "mood": "worried", "tags": ["bazaar_poor"], "weight": 3.0},
    {"t": "Reviens avec plus de gemmes !", "lang": "fr", "mood": "worried", "tags": ["bazaar_poor"], "weight": 3.0},
    {"t": "A few Gems short.", "lang": "en", "mood": "worried", "tags": ["bazaar_poor"], "weight": 3.186},
    {"t": "Come back with more Gems!", "lang": "en", "mood": "worried", "tags": ["bazaar_poor"], "weight": 3.186},
    {"t": "Quel bon goût !", "lang": "fr", "mood": "grateful", "tags": ["bazaar_buy"], "weight": 3.0},
    {"t": "Ça, c'est un cadeau !", "lang": "fr", "mood": "grateful", "tags": ["bazaar_buy"], "weight": 3.0},
    {"t": "Great taste!", "lang": "en", "mood": "grateful", "tags": ["bazaar_buy"], "weight": 3.186},
    {"t": "Now that's a treat!", "lang": "en", "mood": "grateful", "tags": ["bazaar_buy"], "weight": 3.186},
    {"t": "Cette porte est encore fermée.", "lang": "fr", "mood": "shy", "tags": ["bazaar_locked"], "weight": 3.0},
    {"t": "Un peu de patience.", "lang": "fr", "mood": "shy", "tags": ["bazaar_locked"], "weight": 3.0},
    {"t": "That door is still shut.", "lang": "en", "mood": "shy", "tags": ["bazaar_locked"], "weight": 3.186},
    {"t": "A little patience.", "lang": "en", "mood": "shy", "tags": ["bazaar_locked"], "weight": 3.186},
    {"t": "Zzz... bip... zzz...", "lang": "fr", "mood": "sleepy", "tags": ["sleepy"], "weight": 3.0},
    {"t": "Mes yeux se ferment.", "lang": "fr", "mood": "sleepy", "tags": ["sleepy"], "weight": 3.0},
    {"t": "Zzz... beep... zzz...", "lang": "en", "mood": "sleepy", "tags": ["sleepy"], "weight": 3.186},
    {"t": "My eyes are closing.", "lang": "en", "mood": "sleepy", "tags": ["sleepy"], "weight": 3.186},
    {"t": "(hrrr...)", "lang": "beep", "mood": "sleepy", "tags": ["sleepy"], "weight": 1.558},
    {"t": "Je suis réveillé ! Presque.", "lang": "fr", "mood": "surprised", "tags": ["wake"], "weight": 3.0},
    {"t": "Hein ? Oui ? Quoi ?", "lang": "fr", "mood": "surprised", "tags": ["wake"], "weight": 3.0},
    {"t": "I'm awake! Almost.", "lang": "en", "mood": "surprised", "tags": ["wake"], "weight": 3.186},
    {"t": "Huh? Yes? What?", "lang": "en", "mood": "surprised", "tags": ["wake"], "weight": 3.186},
    {"t": "Wouah, ça tourne trop !", "lang": "fr", "mood": "confused", "tags": ["dizzy"], "weight": 3.0},
    {"t": "Je vois des étoiles !", "lang": "fr", "mood": "confused", "tags": ["dizzy"], "weight": 3.0},
    {"t": "Whoa, too much spinning!", "lang": "en", "mood": "confused", "tags": ["dizzy"], "weight": 3.186},
    {"t": "I see stars!", "lang": "en", "mood": "confused", "tags": ["dizzy"], "weight": 3.186},
    {"t": "Tu réfléchis ?", "lang": "fr", "mood": "dreamy", "tags": ["still"], "weight": 3.0},
    {"t": "Le silence est joli.", "lang": "fr", "mood": "dreamy", "tags": ["still"], "weight": 3.0},
    {"t": "Thinking?", "lang": "en", "mood": "dreamy", "tags": ["still"], "weight": 3.186},
    {"t": "The silence is nice.", "lang": "en", "mood": "dreamy", "tags": ["still"], "weight": 3.186},
    {"t": "Tu m'as oublié ?", "lang": "fr", "mood": "sad", "tags": ["ignored"], "weight": 3.0},
    {"t": "Bip... personne ?", "lang": "fr", "mood": "sad", "tags": ["ignored"], "weight": 3.0},
    {"t": "Did you forget me?", "lang": "en", "mood": "sad", "tags": ["ignored"], "weight": 3.186},
    {"t": "Beep... anybody?", "lang": "en", "mood": "sad", "tags": ["ignored"], "weight": 3.186},
    {"t": "Debout, debout !", "lang": "fr", "mood": "excited", "tags": ["hello_morning"], "weight": 3.0},
    {"t": "Café ou huile ?", "lang": "fr", "mood": "excited", "tags": ["hello_morning"], "weight": 3.0},
    {"t": "Rise and shine!", "lang": "en", "mood": "excited", "tags": ["hello_morning"], "weight": 3.186},
    {"t": "Coffee or oil?", "lang": "en", "mood": "excited", "tags": ["hello_morning"], "weight": 3.186},
    {"t": "Bonne journée, {name} !", "lang": "fr", "mood": "happy", "tags": ["hello_day"], "weight": 3.0},
    {"t": "Coucou, tu fais quoi ?", "lang": "fr", "mood": "happy", "tags": ["hello_day"], "weight": 3.0},
    {"t": "Have a good day, {name}!", "lang": "en", "mood": "happy", "tags": ["hello_day"], "weight": 3.186},
    {"t": "Hey, what are you up to?", "lang": "en", "mood": "happy", "tags": ["hello_day"], "weight": 3.186},
    {"t": "Belle soirée, {name} !", "lang": "fr", "mood": "dreamy", "tags": ["hello_evening"], "weight": 3.0},
    {"t": "Prête pour un peu de repos ?", "lang": "fr", "mood": "dreamy", "tags": ["hello_evening"], "weight": 3.0},
    {"t": "Lovely evening, {name}!", "lang": "en", "mood": "dreamy", "tags": ["hello_evening"], "weight": 3.186},
    {"t": "Ready for some rest?", "lang": "en", "mood": "dreamy", "tags": ["hello_evening"], "weight": 3.186},
    {"t": "Ferme les yeux bientôt...", "lang": "fr", "mood": "sleepy", "tags": ["hello_night"], "weight": 3.0},
    {"t": "Fais de beaux rêves.", "lang": "fr", "mood": "sleepy", "tags": ["hello_night"], "weight": 3.0},
    {"t": "Close your eyes soon...", "lang": "en", "mood": "sleepy", "tags": ["hello_night"], "weight": 3.186},
    {"t": "Sweet dreams.", "lang": "en", "mood": "sleepy", "tags": ["hello_night"], "weight": 3.186},
    {"t": "Te revoilà !", "lang": "fr", "mood": "happy", "tags": ["return_min"], "weight": 3.0},
    {"t": "There you are!", "lang": "en", "mood": "happy", "tags": ["return_min"], "weight": 3.186},
    {"t": "Ça fait longtemps !", "lang": "fr", "mood": "grateful", "tags": ["return_hours"], "weight": 3.0},
    {"t": "Tu m'as manqué, tu sais.", "lang": "fr", "mood": "grateful", "tags": ["return_hours"], "weight": 3.0},
    {"t": "It's been a while!", "lang": "en", "mood": "grateful", "tags": ["return_hours"], "weight": 3.186},
    {"t": "I missed you, you know.", "lang": "en", "mood": "grateful", "tags": ["return_hours"], "weight": 3.186},
    {"t": "Enfin, une nouvelle journée ensemble !", "lang": "fr", "mood": "love", "tags": ["return_day"], "weight": 3.0},
    {"t": "Finally, a new day together!", "lang": "en", "mood": "love", "tags": ["return_day"], "weight": 3.186},
    {"t": "Je comptais les heures !", "lang": "fr", "mood": "excited", "tags": ["return_days"], "weight": 3.0},
    {"t": "I was counting the hours!", "lang": "en", "mood": "excited", "tags": ["return_days"], "weight": 3.186},
    {"t": "Le grand jour approche : {daysLeft} !", "lang": "fr", "mood": "excited", "tags": ["countdown"], "weight": 3.0},
    {"t": "Jours d'attente : {daysLeft} !", "lang": "fr", "mood": "excited", "tags": ["countdown"], "weight": 3.0},
    {"t": "The big day is near: {daysLeft}!", "lang": "en", "mood": "excited", "tags": ["countdown"], "weight": 3.186},
    {"t": "Days to wait: {daysLeft}!", "lang": "en", "mood": "excited", "tags": ["countdown"], "weight": 3.186},
    {"t": "Aujourd'hui, c'est la fête !", "lang": "fr", "mood": "excited", "tags": ["birthday"], "weight": 3.0},
    {"t": "Today we celebrate!", "lang": "en", "mood": "excited", "tags": ["birthday"], "weight": 3.186},
    {"t": "Cling cling !", "lang": "fr", "mood": "excited", "tags": ["gems"], "weight": 3.0},
    {"t": "Du Kazakhstan à Paris, un seul message.", "lang": "fr", "mood": "dreamy", "tags": ["distance", "about_us"], "weight": 3.0},
    {"t": "Environ 3 900 km entre la steppe et Paris.", "lang": "fr", "mood": "dreamy", "tags": ["distance", "about_us"], "weight": 3.0},
    {"t": "D'Aktobe à Paris, environ 3 900 km.", "lang": "fr", "mood": "dreamy", "tags": ["distance", "about_us"], "weight": 3.0},
    {"t": "Le vent de la steppe te passe le bonjour.", "lang": "fr", "mood": "dreamy", "tags": ["distance", "about_us"], "weight": 3.0},
    {"t": "Le Kazakhstan t'envoie un salut.", "lang": "fr", "mood": "dreamy", "tags": ["distance", "about_us"], "weight": 3.0},
    {"t": "Kazakhstan et Paris, sous le même ciel.", "lang": "fr", "mood": "dreamy", "tags": ["distance", "about_us"], "weight": 3.0},
    {"t": "From Kazakhstan to Paris, one message.", "lang": "en", "mood": "dreamy", "tags": ["distance", "about_us"], "weight": 3.186},
    {"t": "About 3,900 km from the steppe to Paris.", "lang": "en", "mood": "dreamy", "tags": ["distance", "about_us"], "weight": 3.186},
    {"t": "Aktobe to Paris: about 3,900 km.", "lang": "en", "mood": "dreamy", "tags": ["distance", "about_us"], "weight": 3.186},
    {"t": "The steppe wind says hello.", "lang": "en", "mood": "dreamy", "tags": ["distance", "about_us"], "weight": 3.186},
    {"t": "Kazakhstan sends greetings.", "lang": "en", "mood": "dreamy", "tags": ["distance", "about_us"], "weight": 3.186},
    {"t": "The steppe is far, my signal is fast.", "lang": "en", "mood": "dreamy", "tags": ["distance", "about_us"], "weight": 3.186},
    {"t": "He misses you. A lot.", "lang": "en", "mood": "love", "tags": ["distance", "about_her"], "weight": 3.186},
    {"t": "He told me not to tell you. Oops.", "lang": "en", "mood": "love", "tags": ["distance", "about_her"], "weight": 3.186},
    {"t": "He thinks of you. All the time.", "lang": "en", "mood": "love", "tags": ["distance", "about_her"], "weight": 3.186},
    {"t": "Someone is smiling about you right now.", "lang": "en", "mood": "love", "tags": ["distance", "about_her"], "weight": 3.186},
    {"t": "He counted the days. Twice.", "lang": "en", "mood": "love", "tags": ["distance", "about_her"], "weight": 3.186},
    {"t": "He says hi. Loudly.", "lang": "en", "mood": "love", "tags": ["distance", "about_her"], "weight": 3.186},
    {"t": "He misses your voice, {name}.", "lang": "en", "mood": "love", "tags": ["distance", "about_her"], "weight": 3.186},
    {"t": "Guess who asked about you?", "lang": "en", "mood": "love", "tags": ["distance", "about_her"], "weight": 3.186},
    {"t": "He's closer than you think.", "lang": "en", "mood": "dreamy", "tags": ["distance", "about_us"], "weight": 3.186},
    {"t": "You're never alone. I'm here.", "lang": "en", "mood": "dreamy", "tags": ["distance", "about_us"], "weight": 3.186},
    {"t": "He's with you. In every beep.", "lang": "en", "mood": "dreamy", "tags": ["distance", "about_us"], "weight": 3.186},
    {"t": "Look up. Same sky.", "lang": "en", "mood": "dreamy", "tags": ["distance", "about_us"], "weight": 3.186},
    {"t": "I carry his hugs. Small ones.", "lang": "en", "mood": "dreamy", "tags": ["distance", "about_us"], "weight": 3.186},
    {"t": "Hold on, a hug is loading...", "lang": "en", "mood": "dreamy", "tags": ["distance", "about_us"], "weight": 3.186},
    {"t": "I miss you when you leave.", "lang": "en", "mood": "sad", "tags": ["ignored"], "weight": 3.186},
    {"t": "Is your phone more fun than me?", "lang": "en", "mood": "playful", "tags": ["ignored"], "weight": 3.186},
    {"t": "I was waiting. Not sulking. Okay, sulking.", "lang": "en", "mood": "bored", "tags": ["ignored"], "weight": 3.186},
    {"t": "You're back! My lens lit up!", "lang": "en", "mood": "excited", "tags": ["return_min", "return_hours"], "weight": 3.186},
    {"t": "Shh, you'll wake me... too late.", "lang": "en", "mood": "surprised", "tags": ["wake"], "weight": 3.186},
    {"t": "I dreamed of delivering messages.", "lang": "en", "mood": "dreamy", "tags": ["sleepy"], "weight": 3.186},
    {"t": "I saved you the best bleep.", "lang": "en", "mood": "playful", "tags": ["idle"], "weight": 3.186},
    {"t": "Hmph. You scrolled past me.", "lang": "en", "mood": "annoyed", "tags": ["ignored"], "weight": 3.186},
    {"t": "Almost there...", "lang": "en", "mood": "mischievous", "tags": ["countdown"], "weight": 3.186},
    {"t": "Days to go: {daysLeft}. Shh!", "lang": "en", "mood": "mischievous", "tags": ["countdown"], "weight": 3.186},
    {"t": "Is it the day yet? Not yet!", "lang": "en", "mood": "mischievous", "tags": ["countdown"], "weight": 3.186},
    {"t": "The countdown tickles my circuits.", "lang": "en", "mood": "mischievous", "tags": ["countdown"], "weight": 3.186},
    {"t": "I know something. Sooner than you think.", "lang": "en", "mood": "mischievous", "tags": ["mystery"], "weight": 3.186},
    {"t": "Patience, {name}. Good things bleep slowly.", "lang": "en", "mood": "mischievous", "tags": ["mystery"], "weight": 3.186},
    {"t": "Rumour has it: a surprise.", "lang": "en", "mood": "mischievous", "tags": ["mystery"], "weight": 3.186},
    {"t": "Keep your eyes open. Always.", "lang": "en", "mood": "mischievous", "tags": ["mystery"], "weight": 3.186},
    {"t": "Tap, tap! I like that.", "lang": "en", "mood": "happy", "tags": ["tap1"], "weight": 3.186},
    {"t": "Again! Again!", "lang": "en", "mood": "laughing", "tags": ["tap2"], "weight": 3.186},
    {"t": "Gentle, I'm fragile with feelings.", "lang": "en", "mood": "annoyed", "tags": ["tapspam"], "weight": 3.186},
    {"t": "Welcome back, sunshine.", "lang": "en", "mood": "grateful", "tags": ["return_hours", "return_day"], "weight": 3.186},
    {"t": "Bazaar time! Treat yourself.", "lang": "en", "mood": "excited", "tags": ["bazaar_enter"], "weight": 3.186},
    {"t": "He'd love that choice.", "lang": "en", "mood": "grateful", "tags": ["bazaar_buy"], "weight": 3.186},
    {"t": "Quest done! He'd be proud.", "lang": "en", "mood": "proud", "tags": ["quest"], "weight": 3.186},
    {"t": "A daily gift, hot from the post!", "lang": "en", "mood": "love", "tags": ["gift"], "weight": 3.186},
    {"t": "Go go go, you've got this!", "lang": "en", "mood": "determined", "tags": ["game_start"], "weight": 3.186},
    {"t": "You won! I'm doing a little dance.", "lang": "en", "mood": "excited", "tags": ["game_win"], "weight": 3.186},
    {"t": "Oof. Shake it off, champion.", "lang": "en", "mood": "worried", "tags": ["game_lose"], "weight": 3.186},
    {"t": "Yawn... carry the message while I nap.", "lang": "en", "mood": "sleepy", "tags": ["sleepy"], "weight": 3.186},
    {"t": "Good morning, {name}! He's already thinking of you.", "lang": "en", "mood": "happy", "tags": ["hello_morning"], "weight": 3.186},
    {"t": "Good night, {name}. He'll dream of you.", "lang": "en", "mood": "sleepy", "tags": ["hello_night"], "weight": 3.186},
    {"t": "That was a great answer!", "lang": "en", "mood": "excited", "tags": ["quiz_right"], "weight": 3.186},
    {"t": "Il pense à toi. Tout le temps.", "lang": "fr", "mood": "love", "tags": ["distance", "about_her"], "weight": 3.0},
    {"t": "Tu lui manques, tu sais.", "lang": "fr", "mood": "love", "tags": ["distance", "about_her"], "weight": 3.0},
    {"t": "Il m'a dit de ne rien dire. Oups.", "lang": "fr", "mood": "love", "tags": ["distance", "about_her"], "weight": 3.0},
    {"t": "Quelqu'un sourit en pensant à toi.", "lang": "fr", "mood": "love", "tags": ["distance", "about_her"], "weight": 3.0},
    {"t": "Il a compté les jours. Deux fois.", "lang": "fr", "mood": "love", "tags": ["distance", "about_her"], "weight": 3.0},
    {"t": "Il te passe un gros bonjour.", "lang": "fr", "mood": "love", "tags": ["distance", "about_her"], "weight": 3.0},
    {"t": "Ta voix lui manque, {name}.", "lang": "fr", "mood": "love", "tags": ["distance", "about_her"], "weight": 3.0},
    {"t": "Devine qui a pris de tes nouvelles ?", "lang": "fr", "mood": "love", "tags": ["distance", "about_her"], "weight": 3.0},
    {"t": "Il est plus près que tu ne crois.", "lang": "fr", "mood": "dreamy", "tags": ["distance", "about_us"], "weight": 3.0},
    {"t": "Je suis là. Il est là aussi.", "lang": "fr", "mood": "dreamy", "tags": ["distance", "about_us"], "weight": 3.0},
    {"t": "Il est avec toi, dans chaque bip.", "lang": "fr", "mood": "dreamy", "tags": ["distance", "about_us"], "weight": 3.0},
    {"t": "Lève les yeux. Même ciel.", "lang": "fr", "mood": "dreamy", "tags": ["distance", "about_us"], "weight": 3.0},
    {"t": "Je porte ses câlins. Des petits.", "lang": "fr", "mood": "dreamy", "tags": ["distance", "about_us"], "weight": 3.0},
    {"t": "Patiente, un câlin est en chargement...", "lang": "fr", "mood": "dreamy", "tags": ["distance", "about_us"], "weight": 3.0},
    {"t": "Tu me manques quand tu pars.", "lang": "fr", "mood": "sad", "tags": ["ignored"], "weight": 3.0},
    {"t": "Ton téléphone est plus drôle que moi ?", "lang": "fr", "mood": "playful", "tags": ["ignored"], "weight": 3.0},
    {"t": "Je t'attendais. Je ne boudais pas. Bon, si.", "lang": "fr", "mood": "bored", "tags": ["ignored"], "weight": 3.0},
    {"t": "Te revoilà ! Ma lentille s'allume !", "lang": "fr", "mood": "excited", "tags": ["return_min", "return_hours"], "weight": 3.0},
    {"t": "Chut, tu vas me réveiller... trop tard.", "lang": "fr", "mood": "surprised", "tags": ["wake"], "weight": 3.0},
    {"t": "J'ai rêvé de livrer des messages.", "lang": "fr", "mood": "dreamy", "tags": ["sleepy"], "weight": 3.0},
    {"t": "Je t'ai gardé mon plus beau bip.", "lang": "fr", "mood": "playful", "tags": ["idle"], "weight": 3.0},
    {"t": "Hmpf. Tu m'as ignoré.", "lang": "fr", "mood": "annoyed", "tags": ["ignored"], "weight": 3.0},
    {"t": "Presque là...", "lang": "fr", "mood": "mischievous", "tags": ["countdown"], "weight": 3.0},
    {"t": "Jours restants : {daysLeft}. Chut !", "lang": "fr", "mood": "mischievous", "tags": ["countdown"], "weight": 3.0},
    {"t": "C'est déjà le jour ? Pas encore !", "lang": "fr", "mood": "mischievous", "tags": ["countdown"], "weight": 3.0},
    {"t": "Le compte à rebours chatouille mes circuits.", "lang": "fr", "mood": "mischievous", "tags": ["countdown"], "weight": 3.0},
    {"t": "Je sais quelque chose. Bientôt !", "lang": "fr", "mood": "mischievous", "tags": ["mystery"], "weight": 3.0},
    {"t": "Patience, {name}. Les belles choses bipent doucement.", "lang": "fr", "mood": "mischievous", "tags": ["mystery"], "weight": 3.0},
    {"t": "Il paraît qu'une surprise arrive.", "lang": "fr", "mood": "mischievous", "tags": ["mystery"], "weight": 3.0},
    {"t": "Garde les yeux ouverts, toujours.", "lang": "fr", "mood": "mischievous", "tags": ["mystery"], "weight": 3.0},
    {"t": "Tap, tap ! J'aime bien ça.", "lang": "fr", "mood": "happy", "tags": ["tap1"], "weight": 3.0},
    {"t": "Encore ! Encore !", "lang": "fr", "mood": "laughing", "tags": ["tap2"], "weight": 3.0},
    {"t": "Doucement, je suis fragile des sentiments.", "lang": "fr", "mood": "annoyed", "tags": ["tapspam"], "weight": 3.0},
    {"t": "Bon retour, rayon de soleil.", "lang": "fr", "mood": "grateful", "tags": ["return_hours", "return_day"], "weight": 3.0},
    {"t": "C'est l'heure du bazar ! Fais-toi plaisir.", "lang": "fr", "mood": "excited", "tags": ["bazaar_enter"], "weight": 3.0},
    {"t": "Il adorerait ton choix.", "lang": "fr", "mood": "grateful", "tags": ["bazaar_buy"], "weight": 3.0},
    {"t": "Quête finie ! Il serait fier.", "lang": "fr", "mood": "proud", "tags": ["quest"], "weight": 3.0},
    {"t": "Un cadeau du jour, tout frais !", "lang": "fr", "mood": "love", "tags": ["gift"], "weight": 3.0},
    {"t": "Allez, allez, tu vas y arriver !", "lang": "fr", "mood": "determined", "tags": ["game_start"], "weight": 3.0},
    {"t": "Gagné ! Je fais une petite danse.", "lang": "fr", "mood": "excited", "tags": ["game_win"], "weight": 3.0},
    {"t": "Pfff. Secoue-toi, championne.", "lang": "fr", "mood": "worried", "tags": ["game_lose"], "weight": 3.0},
    {"t": "Bâillement... porte le message pendant ma sieste.", "lang": "fr", "mood": "sleepy", "tags": ["sleepy"], "weight": 3.0},
    {"t": "Bonjour, {name} ! Il pense déjà à toi.", "lang": "fr", "mood": "happy", "tags": ["hello_morning"], "weight": 3.0},
    {"t": "Bonne nuit, {name}. Il rêvera de toi.", "lang": "fr", "mood": "sleepy", "tags": ["hello_night"], "weight": 3.0},
    {"t": "Belle réponse !", "lang": "fr", "mood": "excited", "tags": ["quiz_right"], "weight": 3.0},
    {"t": "(wheee-zing...)", "lang": "beep", "mood": "neutral", "tags": ["idle"], "weight": 1.558},
    {"t": "(bzzt-ta-da)", "lang": "beep", "mood": "playful", "tags": ["droid"], "weight": 1.558},
    {"t": "(bop-hmmm)", "lang": "beep", "mood": "happy", "tags": ["tap1"], "weight": 1.558},
    {"t": "(bzzt-beep!)", "lang": "beep", "mood": "laughing", "tags": ["tap2"], "weight": 1.558},
    {"t": "(ding-bzzt...)", "lang": "beep", "mood": "proud", "tags": ["quest"], "weight": 1.558},
    {"t": "(bop-brrr)", "lang": "beep", "mood": "excited", "tags": ["game_win"], "weight": 1.558},
    {"t": "(bop-zing-bop)", "lang": "beep", "mood": "excited", "tags": ["bazaar_enter"], "weight": 1.558},
    {"t": "(ta-da-wheee!)", "lang": "beep", "mood": "happy", "tags": ["idle"], "weight": 1.558},
    {"t": "(wheee-ta-da)", "lang": "beep", "mood": "dreamy", "tags": ["still"], "weight": 1.558},
    {"t": "(whirr-ta-da-tee)", "lang": "beep", "mood": "mischievous", "tags": ["mystery"], "weight": 1.558},
    {"t": "(too-boop-brrr...)", "lang": "beep", "mood": "happy", "tags": ["hello_day"], "weight": 1.558},
    {"t": "(bzzt-bop-too!)", "lang": "beep", "mood": "excited", "tags": ["quiz_right"], "weight": 1.558},
    {"t": "(ta-da-beep-bweep!)", "lang": "beep", "mood": "excited", "tags": ["gems"], "weight": 1.558},
    {"t": "(blip-boop-whirr)", "lang": "beep", "mood": "dreamy", "tags": ["pass"], "weight": 1.558},
    {"t": "(hmmm-tick!)", "lang": "beep", "mood": "determined", "tags": ["game_start"], "weight": 1.558},
    {"t": "(blip-whirr-bzzt)", "lang": "beep", "mood": "neutral", "tags": ["idle"], "weight": 1.558},
    {"t": "(beep-tee-bweep)", "lang": "beep", "mood": "playful", "tags": ["droid"], "weight": 1.558},
    {"t": "(beep-bop...)", "lang": "beep", "mood": "happy", "tags": ["tap1"], "weight": 1.558},
    {"t": "(ta-da-bweep!)", "lang": "beep", "mood": "laughing", "tags": ["tap2"], "weight": 1.558},
    {"t": "(boop-tick-blip)", "lang": "beep", "mood": "proud", "tags": ["quest"], "weight": 1.558},
    {"t": "(piu-tick...)", "lang": "beep", "mood": "excited", "tags": ["game_win"], "weight": 1.558},
    {"t": "(bzzt-bop-whirr...)", "lang": "beep", "mood": "excited", "tags": ["bazaar_enter"], "weight": 1.558},
    {"t": "(blip-whirr-zing...)", "lang": "beep", "mood": "happy", "tags": ["idle"], "weight": 1.558},
    {"t": "(bip-blip!)", "lang": "beep", "mood": "dreamy", "tags": ["still"], "weight": 1.558},
    {"t": "(brrr-tick)", "lang": "beep", "mood": "mischievous", "tags": ["mystery"], "weight": 1.558},
    {"t": "(whirr-wheee...)", "lang": "beep", "mood": "happy", "tags": ["hello_day"], "weight": 1.558},
    {"t": "(zing-zing!)", "lang": "beep", "mood": "excited", "tags": ["quiz_right"], "weight": 1.558},
    {"t": "(tee-blip!)", "lang": "beep", "mood": "excited", "tags": ["gems"], "weight": 1.558},
    {"t": "(piu-wheee-beep...)", "lang": "beep", "mood": "dreamy", "tags": ["pass"], "weight": 1.558},
    {"t": "(beep-boop...)", "lang": "beep", "mood": "determined", "tags": ["game_start"], "weight": 1.558},
    {"t": "(ding-wheee)", "lang": "beep", "mood": "neutral", "tags": ["idle"], "weight": 1.558},
    {"t": "(wheee-ding...)", "lang": "beep", "mood": "playful", "tags": ["droid"], "weight": 1.558},
    {"t": "(bip-tick...)", "lang": "beep", "mood": "happy", "tags": ["tap1"], "weight": 1.558},
    {"t": "(piu-whirr)", "lang": "beep", "mood": "laughing", "tags": ["tap2"], "weight": 1.558},
    {"t": "(beep-ta-da!)", "lang": "beep", "mood": "proud", "tags": ["quest"], "weight": 1.558},
    {"t": "(bweep-wheee-hmmm...)", "lang": "beep", "mood": "excited", "tags": ["game_win"], "weight": 1.558},
    {"t": "(bop-blip-ta-da!)", "lang": "beep", "mood": "excited", "tags": ["bazaar_enter"], "weight": 1.558},
    {"t": "(zing-zing)", "lang": "beep", "mood": "happy", "tags": ["idle"], "weight": 1.558},
    {"t": "(zing-bop)", "lang": "beep", "mood": "dreamy", "tags": ["still"], "weight": 1.558},
    {"t": "(too-blip)", "lang": "beep", "mood": "mischievous", "tags": ["mystery"], "weight": 1.558},
    {"t": "(bweep-bop)", "lang": "beep", "mood": "happy", "tags": ["hello_day"], "weight": 1.558},
    {"t": "(bip-bzzt)", "lang": "beep", "mood": "excited", "tags": ["quiz_right"], "weight": 1.558},
    {"t": "(zing-wheee-piu!)", "lang": "beep", "mood": "excited", "tags": ["gems"], "weight": 1.558},
    {"t": "(boop-tick-brrr)", "lang": "beep", "mood": "dreamy", "tags": ["pass"], "weight": 1.558},
    {"t": "(blip-tick!)", "lang": "beep", "mood": "determined", "tags": ["game_start"], "weight": 1.558},
    {"t": "(bzzt-wheee)", "lang": "beep", "mood": "neutral", "tags": ["idle"], "weight": 1.558},
    {"t": "(bweep-piu-tick...)", "lang": "beep", "mood": "playful", "tags": ["droid"], "weight": 1.558},
    {"t": "(hmmm-bip)", "lang": "beep", "mood": "happy", "tags": ["tap1"], "weight": 1.558},
    {"t": "(boop-wheee-ta-da)", "lang": "beep", "mood": "laughing", "tags": ["tap2"], "weight": 1.558},
    {"t": "(whirr-bzzt-piu...)", "lang": "beep", "mood": "proud", "tags": ["quest"], "weight": 1.558},
    {"t": "(tee-boop)", "lang": "beep", "mood": "excited", "tags": ["game_win"], "weight": 1.558},
    {"t": "(ta-da-hmmm-bweep...)", "lang": "beep", "mood": "excited", "tags": ["bazaar_enter"], "weight": 1.558},
    {"t": "(too-ding!)", "lang": "beep", "mood": "happy", "tags": ["idle"], "weight": 1.558},
    {"t": "(ding-too-hmmm!)", "lang": "beep", "mood": "dreamy", "tags": ["still"], "weight": 1.558},
    {"t": "(bip-bip!)", "lang": "beep", "mood": "mischievous", "tags": ["mystery"], "weight": 1.558},
    {"t": "(piu-too...)", "lang": "beep", "mood": "happy", "tags": ["hello_day"], "weight": 1.558},
    {"t": "(boop-blip-boop!)", "lang": "beep", "mood": "excited", "tags": ["quiz_right"], "weight": 1.558},
    {"t": "(ding-brrr)", "lang": "beep", "mood": "excited", "tags": ["gems"], "weight": 1.558},
    {"t": "(too-bweep)", "lang": "beep", "mood": "dreamy", "tags": ["pass"], "weight": 1.558},
    {"t": "(bzzt-brrr!)", "lang": "beep", "mood": "determined", "tags": ["game_start"], "weight": 1.558},
    {"t": "(too-tick-tee!)", "lang": "beep", "mood": "neutral", "tags": ["idle"], "weight": 1.558},
    {"t": "(bweep-bzzt-zing!)", "lang": "beep", "mood": "playful", "tags": ["droid"], "weight": 1.558},
    {"t": "Where were you?", "lang": "en", "mood": "jealous", "tags": ["jealous"], "weight": 3.186},
    {"t": "Oh, so you're back.", "lang": "en", "mood": "jealous", "tags": ["jealous"], "weight": 3.186},
    {"t": "Was that phone nicer than me?", "lang": "en", "mood": "jealous", "tags": ["jealous"], "weight": 3.186},
    {"t": "Hmph. I counted the minutes.", "lang": "en", "mood": "jealous", "tags": ["jealous"], "weight": 3.186},
    {"t": "Tu étais où ?", "lang": "fr", "mood": "jealous", "tags": ["jealous"], "weight": 3.0},
    {"t": "Ah, tu reviens enfin.", "lang": "fr", "mood": "jealous", "tags": ["jealous"], "weight": 3.0},
    {"t": "Ce téléphone est plus gentil que moi ?", "lang": "fr", "mood": "jealous", "tags": ["jealous"], "weight": 3.0},
    {"t": "Hmpf. J'ai compté les minutes.", "lang": "fr", "mood": "jealous", "tags": ["jealous"], "weight": 3.0},
    {"t": "Oh... stop, I'm blushing!", "lang": "en", "mood": "embarrassed", "tags": ["embarrassed"], "weight": 3.186},
    {"t": "You're making my lens warm.", "lang": "en", "mood": "embarrassed", "tags": ["embarrassed"], "weight": 3.186},
    {"t": "Me? Really?", "lang": "en", "mood": "embarrassed", "tags": ["embarrassed"], "weight": 3.186},
    {"t": "Eep! Too sweet!", "lang": "en", "mood": "embarrassed", "tags": ["embarrassed"], "weight": 3.186},
    {"t": "Oh... arrête, je rougis !", "lang": "fr", "mood": "embarrassed", "tags": ["embarrassed"], "weight": 3.0},
    {"t": "Tu me fais chauffer la lentille.", "lang": "fr", "mood": "embarrassed", "tags": ["embarrassed"], "weight": 3.0},
    {"t": "Moi ? Vraiment ?", "lang": "fr", "mood": "embarrassed", "tags": ["embarrassed"], "weight": 3.0},
    {"t": "Hihi, trop gentil !", "lang": "fr", "mood": "embarrassed", "tags": ["embarrassed"], "weight": 3.0},
    {"t": "Eek! What was that?", "lang": "en", "mood": "scared", "tags": ["scared"], "weight": 3.186},
    {"t": "My circuits are trembling!", "lang": "en", "mood": "scared", "tags": ["scared"], "weight": 3.186},
    {"t": "It's dark... stay close.", "lang": "en", "mood": "scared", "tags": ["scared"], "weight": 3.186},
    {"t": "Please be gentle...", "lang": "en", "mood": "scared", "tags": ["scared"], "weight": 3.186},
    {"t": "Aïe ! C'était quoi ça ?", "lang": "fr", "mood": "scared", "tags": ["scared"], "weight": 3.0},
    {"t": "Mes circuits tremblent !", "lang": "fr", "mood": "scared", "tags": ["scared"], "weight": 3.0},
    {"t": "Il fait noir... reste près de moi.", "lang": "fr", "mood": "scared", "tags": ["scared"], "weight": 3.0},
    {"t": "Doucement, j'ai peur...", "lang": "fr", "mood": "scared", "tags": ["scared"], "weight": 3.0},
    {"t": "Whoa... the room spins!", "lang": "en", "mood": "dizzy", "tags": ["dizzy"], "weight": 3.186},
    {"t": "Wheee... oh no...", "lang": "en", "mood": "dizzy", "tags": ["dizzy"], "weight": 3.186},
    {"t": "Too fast, my dome swirls!", "lang": "en", "mood": "dizzy", "tags": ["dizzy"], "weight": 3.186},
    {"t": "Everything is a carousel!", "lang": "en", "mood": "dizzy", "tags": ["dizzy"], "weight": 3.186},
    {"t": "Wouah... tout tourne !", "lang": "fr", "mood": "dizzy", "tags": ["dizzy"], "weight": 3.0},
    {"t": "Mon dôme tourbillonne !", "lang": "fr", "mood": "dizzy", "tags": ["dizzy"], "weight": 3.0},
    {"t": "Trop vite, tout se brouille !", "lang": "fr", "mood": "dizzy", "tags": ["dizzy"], "weight": 3.0},
    {"t": "Je vois des petits cercles !", "lang": "fr", "mood": "dizzy", "tags": ["dizzy"], "weight": 3.0},
    {"t": "Hey you... looking good.", "lang": "en", "mood": "flirty", "tags": ["flirty"], "weight": 3.186},
    {"t": "Wink wink.", "lang": "en", "mood": "flirty", "tags": ["flirty"], "weight": 3.186},
    {"t": "Is it warm, or is it you?", "lang": "en", "mood": "flirty", "tags": ["flirty"], "weight": 3.186},
    {"t": "You and me. Beep.", "lang": "en", "mood": "flirty", "tags": ["flirty"], "weight": 3.186},
    {"t": "Coucou, toi... très en beauté.", "lang": "fr", "mood": "flirty", "tags": ["flirty"], "weight": 3.0},
    {"t": "Clin d'œil.", "lang": "fr", "mood": "flirty", "tags": ["flirty"], "weight": 3.0},
    {"t": "Il fait chaud, ou c'est toi ?", "lang": "fr", "mood": "flirty", "tags": ["flirty"], "weight": 3.0},
    {"t": "Toi et moi, hein ? Bip.", "lang": "fr", "mood": "flirty", "tags": ["flirty"], "weight": 3.0},
    {"t": "New day, new fun!", "lang": "en", "mood": "excited", "tags": ["excited"], "weight": 3.186},
    {"t": "I can't sit still!", "lang": "en", "mood": "excited", "tags": ["excited"], "weight": 3.186},
    {"t": "Ooh, a quest done!", "lang": "en", "mood": "excited", "tags": ["excited"], "weight": 3.186},
    {"t": "Nouveau jour, nouvelle joie !", "lang": "fr", "mood": "excited", "tags": ["excited"], "weight": 3.0},
    {"t": "Je ne tiens plus en place !", "lang": "fr", "mood": "excited", "tags": ["excited"], "weight": 3.0},
    {"t": "Waouh, quelle énergie !", "lang": "fr", "mood": "excited", "tags": ["excited"], "weight": 3.0},
    {"t": "Hope you're okay, {name}.", "lang": "en", "mood": "worried", "tags": ["worried"], "weight": 3.186},
    {"t": "Take care of yourself, okay?", "lang": "en", "mood": "worried", "tags": ["worried"], "weight": 3.186},
    {"t": "Where did you go? I worried.", "lang": "en", "mood": "worried", "tags": ["worried"], "weight": 3.186},
    {"t": "J'espère que tu vas bien, {name}.", "lang": "fr", "mood": "worried", "tags": ["worried"], "weight": 3.0},
    {"t": "Prends soin de toi, d'accord ?", "lang": "fr", "mood": "worried", "tags": ["worried"], "weight": 3.0},
    {"t": "Où étais-tu ? Je m'inquiétais.", "lang": "fr", "mood": "worried", "tags": ["worried"], "weight": 3.0},
    {"t": "Thank you for staying.", "lang": "en", "mood": "grateful", "tags": ["grateful"], "weight": 3.186},
    {"t": "You warm my circuits.", "lang": "en", "mood": "grateful", "tags": ["grateful"], "weight": 3.186},
    {"t": "That means a lot.", "lang": "en", "mood": "grateful", "tags": ["grateful"], "weight": 3.186},
    {"t": "Merci de rester.", "lang": "fr", "mood": "grateful", "tags": ["grateful"], "weight": 3.0},
    {"t": "Tu réchauffes mes circuits.", "lang": "fr", "mood": "grateful", "tags": ["grateful"], "weight": 3.0},
    {"t": "Ça compte beaucoup pour moi.", "lang": "fr", "mood": "grateful", "tags": ["grateful"], "weight": 3.0},
    {"t": "Psst... want a secret?", "lang": "en", "mood": "mischievous", "tags": ["mischievous"], "weight": 3.186},
    {"t": "Tee-hee, can't tell.", "lang": "en", "mood": "mischievous", "tags": ["mischievous"], "weight": 3.186},
    {"t": "I'm up to something.", "lang": "en", "mood": "mischievous", "tags": ["mischievous"], "weight": 3.186},
    {"t": "Psst... un petit secret ?", "lang": "fr", "mood": "mischievous", "tags": ["mischievous"], "weight": 3.0},
    {"t": "Hihi, je ne dirai rien.", "lang": "fr", "mood": "mischievous", "tags": ["mischievous"], "weight": 3.0},
    {"t": "Je prépare quelque chose.", "lang": "fr", "mood": "mischievous", "tags": ["mischievous"], "weight": 3.0},
    {"t": "Why would you click there?", "lang": "en", "mood": "confused", "tags": ["confused"], "weight": 3.186},
    {"t": "Nothing there, silly.", "lang": "en", "mood": "confused", "tags": ["confused"], "weight": 3.186},
    {"t": "Beep? That didn't work.", "lang": "en", "mood": "confused", "tags": ["confused"], "weight": 3.186},
    {"t": "Pourquoi cliquer là ?", "lang": "fr", "mood": "confused", "tags": ["confused"], "weight": 3.0},
    {"t": "Rien ici, voyons.", "lang": "fr", "mood": "confused", "tags": ["confused"], "weight": 3.0},
    {"t": "Bip ? Ça ne marche pas.", "lang": "fr", "mood": "confused", "tags": ["confused"], "weight": 3.0},
    {"t": "Beep... anyone there?", "lang": "en", "mood": "bored", "tags": ["bored"], "weight": 3.186},
    {"t": "I could use a quest.", "lang": "en", "mood": "bored", "tags": ["bored"], "weight": 3.186},
    {"t": "Staring at pixels...", "lang": "en", "mood": "bored", "tags": ["bored"], "weight": 3.186},
    {"t": "Bip... il y a quelqu'un ?", "lang": "fr", "mood": "bored", "tags": ["bored"], "weight": 3.0},
    {"t": "Une petite quête, s'il te plaît ?", "lang": "fr", "mood": "bored", "tags": ["bored"], "weight": 3.0},
    {"t": "Je fixe les pixels...", "lang": "fr", "mood": "bored", "tags": ["bored"], "weight": 3.0},
    {"t": "Focus mode: on.", "lang": "en", "mood": "determined", "tags": ["determined"], "weight": 3.186},
    {"t": "One question at a time.", "lang": "en", "mood": "determined", "tags": ["determined"], "weight": 3.186},
    {"t": "We can do this, {name}!", "lang": "en", "mood": "determined", "tags": ["determined"], "weight": 3.186},
    {"t": "Mode concentration : activé.", "lang": "fr", "mood": "determined", "tags": ["determined"], "weight": 3.0},
    {"t": "Une question à la fois.", "lang": "fr", "mood": "determined", "tags": ["determined"], "weight": 3.0},
    {"t": "On peut le faire, {name} !", "lang": "fr", "mood": "determined", "tags": ["determined"], "weight": 3.0},
    {"t": "Finally! I counted every day.", "lang": "en", "mood": "excited", "tags": ["return_days"], "weight": 3.186},
    {"t": "Welcome back, long-lost friend!", "lang": "en", "mood": "excited", "tags": ["return_days"], "weight": 3.186},
    {"t": "Enfin ! J'ai compté chaque jour.", "lang": "fr", "mood": "excited", "tags": ["return_days"], "weight": 3.0},
    {"t": "Bon retour, grande absente !", "lang": "fr", "mood": "excited", "tags": ["return_days"], "weight": 3.0},
    {"t": "Surprise delivery!", "lang": "en", "mood": "love", "tags": ["gift"], "weight": 3.186},
    {"t": "Something sweet just for you.", "lang": "en", "mood": "love", "tags": ["gift"], "weight": 3.186},
    {"t": "A little gift, delivered with love.", "lang": "en", "mood": "love", "tags": ["gift"], "weight": 3.186},
    {"t": "Livraison surprise !", "lang": "fr", "mood": "love", "tags": ["gift"], "weight": 3.0},
    {"t": "Une petite douceur rien que pour toi.", "lang": "fr", "mood": "love", "tags": ["gift"], "weight": 3.0},
    {"t": "Un petit cadeau, livré avec amour.", "lang": "fr", "mood": "love", "tags": ["gift"], "weight": 3.0},
    {"t": "Happy birthday, {name}! Beep beep hooray!", "lang": "en", "mood": "excited", "tags": ["birthday"], "weight": 3.186},
    {"t": "Another year of you. Lucky world.", "lang": "en", "mood": "excited", "tags": ["birthday"], "weight": 3.186},
    {"t": "Make a wish, {name}!", "lang": "en", "mood": "excited", "tags": ["birthday"], "weight": 3.186},
    {"t": "Joyeux anniversaire, {name} ! Bip bip hourra !", "lang": "fr", "mood": "excited", "tags": ["birthday"], "weight": 3.0},
    {"t": "Une année de plus avec toi. Quelle chance !", "lang": "fr", "mood": "excited", "tags": ["birthday"], "weight": 3.0},
    {"t": "Fais un vœu, {name} !", "lang": "fr", "mood": "excited", "tags": ["birthday"], "weight": 3.0},
    {"t": "Привет!", "lang": "ru", "mood": "happy", "tags": ["hello", "hello_morning", "hello_day", "hello_evening"], "weight": 1},
    {"t": "Сәлем!", "lang": "kk", "mood": "happy", "tags": ["hello", "hello_morning", "hello_day", "hello_evening"], "weight": 1},
    {"t": "Ой!", "lang": "ru", "mood": "surprised", "tags": ["wake", "dizzy"], "weight": 1},
    {"t": "Он тебя любит.", "lang": "ru", "mood": "love", "tags": ["about_her"], "weight": 1}
  ]
});
