/* ==========================================================================
   R2's mind: emotions, what he says and when. Pure logic (no DOM, no audio),
   so tests/r2.test.js can run it in Node. You do not edit this file.
   Phrases live in content/phrases.js.
   ========================================================================== */
(function (root, factory) {
  if (typeof module === 'object' && module.exports) module.exports = factory();
  else root.R2Brain = factory();
})(typeof globalThis !== 'undefined' ? globalThis : this, function () {
  'use strict';

  const MOODS = ['neutral', 'happy', 'love', 'curious', 'surprised', 'shy', 'sleepy', 'proud', 'laughing', 'sad', 'annoyed', 'angry',
    'excited', 'dreamy', 'mischievous', 'confused', 'worried', 'grateful', 'bored', 'playful', 'determined',
    'jealous', 'embarrassed', 'scared', 'dizzy', 'flirty'];
  /* mood rules: scared/angry beat excited beat the rest; a mood lasts >= 2 s; the expressive ones do not retrigger within 20 s */
  const PRIO = { scared: 3, angry: 3, excited: 2 };
  const COOL = new Set(['excited', 'jealous', 'embarrassed', 'scared', 'worried', 'grateful', 'mischievous', 'confused', 'bored', 'determined', 'dizzy', 'flirty', 'dreamy', 'playful']);
  const FOLLOW = { jealous: ['shy', 3000], embarrassed: ['shy', 2500], scared: ['grateful', 2500], dizzy: ['confused', 1800], grateful: ['happy', 2500], shy: ['happy', 2500] };   // how a mood eases into the next (angry -> annoyed -> shy -> happy is in tick)

  /* what each bus event makes him feel and say. prio: 1 ambient, 2 event, 3 direct answer to a touch */
  const EVENTS = {
    'bazaar:enter':      { tags: ['bazaar_enter'],  mood: 'excited',   ms: 4000, prio: 2 },
    'bazaar:cantAfford': { tags: ['bazaar_poor'],   mood: 'worried',     ms: 3500, prio: 2 },
    'bazaar:locked':     { tags: ['bazaar_locked'], mood: 'shy',       ms: 3000, prio: 2 },
    'bazaar:buy':        { tags: ['bazaar_buy'],    mood: 'grateful',     ms: 5000, prio: 2 },
    'quest:done':        { tags: ['quest'],         mood: 'excited',   ms: 4500, prio: 2 },
    'gift:claim':        { tags: ['gift'],          mood: 'excited',   ms: 5000, prio: 2 },
    'day:new':           { tags: ['excited'],       mood: 'excited',   ms: 5000, prio: 2 },
    'platform:open':     { tags: null, flag: 'leftForPlatform' },
    'ui:empty':          { tags: ['confused'],      mood: 'confused',  ms: 2500, prio: 1 },
    'quiz:question':     { tags: null,              mood: 'determined', ms: 3000, prio: 1 },
    'pass:open':         { tags: ['pass'],          mood: 'dreamy',   ms: 3500, prio: 2 },
    'pass:claim':        { tags: ['pass'],          mood: 'grateful',     ms: 5000, prio: 2 },
    'game:start':        { tags: ['game_start'],    mood: 'determined',   ms: 3500, prio: 2 },
    'game:win':          { tags: ['game_win'],      mood: 'excited',  ms: 5000, prio: 2 },
    'game:lose':         { tags: ['game_lose'],     mood: 'scared',       ms: 3500, prio: 2 },
    'quiz:right':        { tags: ['quiz_right'],    mood: 'happy',     ms: 3500, prio: 2 },
    'quiz:wrong':        { tags: ['quiz_wrong'],    mood: 'curious',   ms: 3000, prio: 2 },
    'gems:gained':       { tags: ['gems'],          mood: 'happy',     ms: 3000, prio: 1 },
    'birthday':          { tags: ['birthday'],      mood: 'love',      ms: 9000, prio: 3 },
    'dizzy':             { tags: ['dizzy'],         mood: 'dizzy',    ms: 3500, prio: 2 }
  };
  const AMBIENT = [['idle', 26], ['about_her', 9], ['about_us', 8], ['distance', 8], ['droid', 9], ['mystery', 9], ['countdown', 6], ['still', 5],
    ['excited', 5], ['dreamy', 7], ['mischievous', 6], ['confused', 3], ['grateful', 4], ['bored', 4], ['playful', 7], ['determined', 3], ['worried', 2], ['flirty', 4]];
  const GAP = { 1: 8000, 2: 8000, 3: 1200 };          // minimum time between two comments (a touch answer may come sooner)
  const STALE = { 1: 5000, 2: 8500, 3: 1500 };         // a comment not said in time is dropped
  const HISTORY = 15;                                  // never repeat the last 15 phrases

  function create(o) {
    const rand = o.rand || Math.random, nowFn = o.now || Date.now;
    let phrases = (o.phrases || []).filter(p => p && p.t);
    const out = o.onSay || (() => {}), onMood = o.onMood || (() => {});
    const S = {
      mood: 'neutral', moodUntil: 0, asleep: false, sad: false,
      lastInput: nowFn(), lastSay: -1e9, speakingUntil: 0, taps: [], angry: false, lastTapAt: 0,
      queue: [], history: [], hiddenAt: 0, lastStart: {}, minUntil: 0, forgiving: false, leftForPlatform: false, bored: false, darkDone: false, sessionStart: nowFn(), activity: 0, nextAmbient: nowFn() + 12000, lastDizzy: -1e9, tapSaid: 0
    };

    function setMood(m, ms, now, force) {
      if (MOODS.indexOf(m) < 0) m = 'neutral';
      if (m === S.mood) { S.moodUntil = ms ? now + ms : 0; return true; }
      if (!force) {
        const pc = PRIO[m] || 1, pn = PRIO[S.mood] || 1;
        if (now < S.minUntil && pc <= pn) return false;                                   // a mood lasts at least 2 s
        if (pn > pc && S.moodUntil && now < S.moodUntil) return false;                  // scared / angry are not interrupted by milder moods
        if (COOL.has(m) && now - (S.lastStart[m] || -1e9) < 20000) return false;        // the same mood does not come back within 20 s
      }
      S.lastStart[m] = now; S.minUntil = now + 2000;
      S.moodUntil = ms ? now + ms : 0; S.mood = m; onMood(m); return true;
    }
    const baseMood = () => (S.asleep ? 'sleepy' : S.sad ? 'sad' : 'neutral');

    /* ---- choosing a phrase ---- */
    function pick(tags, ctx) {
      ctx = ctx || {};
      let pool = phrases.filter(p => p.tags && tags.some(t => p.tags.indexOf(t) >= 0));
      if (!pool.length) return null;
      const fresh = pool.filter(p => S.history.indexOf(p.t) < 0);
      if (fresh.length) pool = fresh;                          // (a tiny pool may have to repeat)
      let total = 0;
      const w = pool.map(p => { const x = (p.weight || 1) * (p.mood === S.mood ? 3 : 1); total += x; return x; });
      let r = rand() * total, chosen = pool[pool.length - 1];
      for (let i = 0; i < pool.length; i++) { r -= w[i]; if (r <= 0) { chosen = pool[i]; break; } }
      S.history.push(chosen.t); if (S.history.length > HISTORY) S.history.shift();
      const name = o.name ? o.name() : '', left = o.daysLeft ? o.daysLeft() : '';
      return { t: chosen.t.replace(/\{name\}/g, name).replace(/\{daysLeft\}/g, left), lang: chosen.lang, mood: chosen.mood || S.mood, tags: chosen.tags };
    }

    /* ---- the queue: priority, minimum gap, stale comments dropped ---- */
    function want(tags, prio, ctx) {
      const now = nowFn();
      if (S.queue.length >= 6) S.queue.sort((a, b) => b.prio - a.prio || a.t - b.t).pop();
      S.queue.push({ tags, prio: prio || 1, t: now, ctx });
      flush();
    }
    function flush() {
      const now = nowFn();
      S.queue = S.queue.filter(q => now - q.t <= STALE[q.prio]);
      if (!S.queue.length) return null;
      S.queue.sort((a, b) => b.prio - a.prio || a.t - b.t);
      const q = S.queue[0], gap = GAP[q.prio];
      if (now - S.lastSay < gap) return null;
      if (q.prio < 3 && now < S.speakingUntil) return null;
      if (S.asleep && q.prio < 3 && q.tags.indexOf('sleepy') < 0) { S.queue.shift(); return null; }
      S.queue.shift();
      const ph = pick(q.tags, q.ctx); if (!ph) return null;
      S.lastSay = now; S.speakingUntil = now + Math.max(1800, ph.t.length * 90 + 900);
      if (q.prio === 1 && !S.asleep && S.mood !== 'angry' && !S.sad) {                    // idle chatter shows a feeling
        let m = ph.mood;
        if (q.tags.indexOf('about_her') >= 0) m = rand() < 0.5 ? 'flirty' : 'embarrassed';  // compliments: flirty or blushing
        else if (q.tags.indexOf('countdown') >= 0 || q.tags.indexOf('flirty') >= 0) m = 'flirty';
        if (MOODS.indexOf(m) >= 0) setMood(m, S.speakingUntil - now + 1200, now);
      }
      out(ph, S.speakingUntil - now);
      return ph;
    }

    /* ---- input from her ---- */
    function input() {
      const now = nowFn(); S.lastInput = now; S.bored = false; S.activity++;
      if (S.asleep) {
        S.asleep = false; S.sad = false; setMood('surprised', 1400, now);
        want(['wake'], 3);
        return 'wake';
      }
      if (S.sad) { S.sad = false; setMood('happy', 2000, now); }
      return null;
    }
    function tap() {
      const now = nowFn(), wasAsleep = S.asleep;
      const r = input(); if (wasAsleep) { S.taps = []; return { n: 0, spoke: true, woke: true }; }
      S.taps = S.taps.filter(t => now - t < 3000); S.taps.push(now); S.lastTapAt = now;
      const n = S.taps.length; let tags = null;
      if (n >= 9) { S.angry = true; setMood('angry', 5000, now, true); if ([9, 11, 14].indexOf(n) >= 0) tags = ['tapangry']; }
      else if (n >= 5) { setMood('annoyed', 4000, now, true); if ([5, 7].indexOf(n) >= 0) tags = ['tapspam']; }
      else if (n === 1) { setMood(S.angry ? 'angry' : 'happy', 2500, now, true); if (!S.angry) tags = ['tap1']; }
      else if (n === 2) { setMood('laughing', 2200, now, true); tags = ['tap2']; }
      else {                                                  // 3rd and 4th tap: fast = surprised, slow and gentle = embarrassed
        if ((now - S.taps[0]) / (n - 1) >= 500) { setMood('embarrassed', 3000, now, true); if (n === 3) tags = ['embarrassed']; }
        else setMood('surprised', 1500, now, true);
      }
      if (tags) want(tags, 3);
      return { n, spoke: !!tags, woke: false, r };
    }

    function event(name, data) {
      const e = EVENTS[name]; if (!e) return;
      const now = nowFn();
      if (e.flag) { S[e.flag] = true; return; }
      if (name !== 'gems:gained') S.lastInput = Math.max(S.lastInput, now - 20000);   // something happening keeps him from dozing off
      if (name !== 'gems:gained' || !S.asleep) setMood(e.mood, e.ms, now);
      if (e.tags) want(e.tags, e.prio, data);
    }

    /* ---- time-based life ---- */
    function ambient(now) {
      let total = 0; AMBIENT.forEach(a => total += a[1]);
      let r = rand() * total, tag = 'idle'; for (const a of AMBIENT) { r -= a[1]; if (r <= 0) { tag = a[0]; break; } }
      S.nextAmbient = now + 25000 + rand() * 25000;
      if (tag === 'countdown' && !(+(o.daysLeft ? o.daysLeft() : 1) >= 1)) tag = 'birthday';
      want([tag], 1);
    }
    function tick(visible) {
      const now = nowFn(); visible = visible !== false;
      if (S.mood !== baseMood() && S.moodUntil && now > S.moodUntil) {
        const was = S.mood; S.moodUntil = 0;
        if (was === 'angry') { S.angry = false; S.forgiving = true; setMood('annoyed', 2500, now, true); }             // angry -> annoyed -> shy -> happy
        else if (was === 'annoyed' && S.forgiving) { S.forgiving = false; setMood('shy', 3500, now, true); want(['forgive'], 3); }
        else if (FOLLOW[was] && !S.asleep) setMood(FOLLOW[was][0], FOLLOW[was][1], now, true);                  // scared -> relieved -> happy ...
        else setMood(baseMood(), 0, now, true);
      } else if (!S.moodUntil && S.mood !== baseMood()) setMood(baseMood(), 0, now, true);
      S.taps = S.taps.filter(t => now - t < 3000);
      if (S.angry && S.mood !== 'angry' && now - S.lastTapAt > 5000) S.angry = false;
      if (!visible) return;
      const idle = now - S.lastInput;
      if (!S.asleep && !S.bored && !S.sad && idle > 22000) { S.bored = true; setMood('bored', 16000, now); want(['bored'], 1); }      // 20-40 s without input: bored
      if (!S.asleep && !S.sad && idle > 40000) { S.sad = true; S.bored = false; setMood('sad', 0, now, true); want(['ignored'], 2); }
      const h = o.hour ? o.hour() : 12;
      if (!S.asleep && !S.darkDone && (h >= 23 || h < 5) && idle > 30000) { S.darkDone = true; if (rand() < 0.5) { setMood('scared', 5000, now); want(['scared'], 2); } }   // a long idle in the dark
      if (!S.asleep && idle > 60000) { S.asleep = true; S.sad = false; S.bored = false; setMood('sleepy', 0, now, true); want(['sleepy'], 3); }
      if (!S.asleep && now >= S.nextAmbient && S.mood !== 'angry') ambient(now);
      flush();
    }

    function pointerSpeed(pxPerSec) {          // wild mouse = dizzy
      const now = nowFn();
      if (S.asleep || pxPerSec < 2500 || now - S.lastDizzy < 20000) return;
      S.lastDizzy = now; event('dizzy');
    }

    /* ---- coming back after a while away (tab hidden, or the page was closed) ---- */
    function away(ms) {
      const m = ms / 60000;
      return m < 3 ? null : m < 30 ? 'return_min' : m < 360 ? 'return_hours' : m < 2160 ? 'return_day' : 'return_days';
    }
    function hidden() { S.hiddenAt = nowFn(); }
    function shown() {
      const now = nowFn(), gone = S.hiddenAt ? now - S.hiddenAt : 0, left = S.leftForPlatform; S.hiddenAt = 0; S.leftForPlatform = false;
      return comeBack(gone, left);
    }
    function comeBack(ms, left) {
      const now = nowFn(), tag = away(ms), good = S.activity >= 10 && now - ms - S.sessionStart > 180000;
      S.lastInput = now; S.asleep = false; S.sad = false; S.bored = false; S.activity = 0; S.sessionStart = now;
      if (tag && ms >= 36 * 3600e3) { setMood('worried', 5000, now, true); want([tag, 'worried'], 3, { ms }); return tag; }     // gone for days: he worried
      if (tag && ms >= 6 * 3600e3) { setMood('jealous', 5000, now, true); want([tag, 'jealous'], 3, { ms }); return tag; }       // gone half a day: "where were you?"
      if (!tag) {
        if (left || ms >= 25000) { setMood('jealous', 3500, now, true); want(['jealous'], 3); } else setMood('neutral', 0, now, true);
        return null;
      }
      if (left) { setMood('jealous', 4000, now, true); want(['jealous'], 3); return tag; }
      if (good) { setMood('grateful', 5000, now, true); want(['grateful', tag], 3, { ms }); return tag; }                           // she said goodbye after a good session
      setMood('happy', 6000, now, true); want([tag], 3, { ms }); return tag;
    }
    /* dev: show a mood with its voice and a sample phrase */
    function preview(m) {
      const now = nowFn(); setMood(m, 3500, now, true);
      const list = phrases.filter(p => p.mood === m); if (!list.length) return null;
      const p = list[Math.floor(rand() * list.length)], name = o.name ? o.name() : '', left = o.daysLeft ? o.daysLeft() : '';
      const ph = { t: p.t.replace(/\{name\}/g, name).replace(/\{daysLeft\}/g, left), lang: p.lang, mood: m, tags: p.tags };
      S.speakingUntil = now + Math.max(1800, ph.t.length * 90 + 900); out(ph, S.speakingUntil - now); return ph;
    }

    function hello(hour) {
      const part = hour >= 5 && hour < 11 ? 'hello_morning' : hour >= 11 && hour < 17 ? 'hello_day' : hour >= 17 && hour < 23 ? 'hello_evening' : 'hello_night';
      setMood('happy', 4000, nowFn()); want([part], 3);
      return part;
    }

    return {
      input, tap, event, tick, pointerSpeed, hidden, shown, comeBack, hello, preview, setPhrases(p) { phrases = p; },
      state: S, mood: () => S.mood, asleep: () => S.asleep, flush, pick, want
    };
  }
  return { create, MOODS, EVENTS, GAP, HISTORY };
});
