/* ==========================================================================
   Core logic: signed save + ledger, trusted clock, game reward sessions.
   Pure code (no DOM) so it also runs in Node for tests/abuse.test.js.
   You do not edit this file. common.js builds the one real instance.
   ========================================================================== */
(function (root, factory) {
  if (typeof module === 'object' && module.exports) module.exports = factory();
  else root.R2Core = factory();
})(typeof globalThis !== 'undefined' ? globalThis : this, function () {
  'use strict';
  const VERSION = 1;
  const DAY_MS = 864e5;

  /* ---------- sha-256 (sync, used to sign the save) ---------- */
  const K = [], H0 = [];
  (function () {
    let p = 2, n = 0;
    while (n < 64) {
      let prime = true; for (let d = 2; d * d <= p; d++) if (p % d === 0) { prime = false; break; }
      if (prime) { if (n < 8) H0.push((Math.pow(p, 0.5) % 1) * 4294967296 | 0); K.push((Math.pow(p, 1 / 3) % 1) * 4294967296 | 0); n++; }
      p++;
    }
  })();
  function sha256(msg) {
    const bytes = new TextEncoder().encode(msg), l = bytes.length, nb = ((l + 9 + 63) >> 6) << 6;
    const buf = new Uint8Array(nb); buf.set(bytes); buf[l] = 0x80;
    const dv = new DataView(buf.buffer); dv.setUint32(nb - 8, Math.floor(l * 8 / 4294967296)); dv.setUint32(nb - 4, (l * 8) >>> 0);
    let h = H0.slice(); const w = new Array(64);
    for (let o = 0; o < nb; o += 64) {
      for (let i = 0; i < 16; i++) w[i] = dv.getUint32(o + i * 4);
      for (let i = 16; i < 64; i++) {
        const a = w[i - 15], b = w[i - 2];
        w[i] = (w[i - 16] + ((a >>> 7 | a << 25) ^ (a >>> 18 | a << 14) ^ (a >>> 3)) + w[i - 7] + ((b >>> 17 | b << 15) ^ (b >>> 19 | b << 13) ^ (b >>> 10))) | 0;
      }
      let [a, b, c, d, e, f, g, hh] = h;
      for (let i = 0; i < 64; i++) {
        const t1 = (hh + ((e >>> 6 | e << 26) ^ (e >>> 11 | e << 21) ^ (e >>> 25 | e << 7)) + ((e & f) ^ (~e & g)) + K[i] + w[i]) | 0;
        const t2 = (((a >>> 2 | a << 30) ^ (a >>> 13 | a << 19) ^ (a >>> 22 | a << 10)) + ((a & b) ^ (a & c) ^ (b & c))) | 0;
        hh = g; g = f; f = e; e = (d + t1) | 0; d = c; c = b; b = a; a = (t1 + t2) | 0;
      }
      h = [h[0] + a | 0, h[1] + b | 0, h[2] + c | 0, h[3] + d | 0, h[4] + e | 0, h[5] + f | 0, h[6] + g | 0, h[7] + hh | 0];
    }
    return h.map(x => (x >>> 0).toString(16).padStart(8, '0')).join('');
  }
  function canonical(v) {
    if (Array.isArray(v)) return '[' + v.map(canonical).join(',') + ']';
    if (v && typeof v === 'object') return '{' + Object.keys(v).sort().map(k => JSON.stringify(k) + ':' + canonical(v[k])).join(',') + '}';
    return JSON.stringify(v === undefined ? null : v);
  }
  const num = v => { v = Math.floor(Number(v)); return isFinite(v) && v > 0 ? Math.min(v, 100000) : 0; };
  const clone = o => JSON.parse(JSON.stringify(o));
  const b64enc = s => btoa(unescape(encodeURIComponent(s)));
  const b64dec = s => decodeURIComponent(escape(atob(s)));

  /* ======================================================================
     SAVE: one key, signed, with one automatic backup copy.
     payload = { v, rev, ledger[], prog{}, modes{}, prefs{}, clock{} }
     ledger entry = { id, kind, gems, xp, day, ts }  (spending = negative gems)
     ====================================================================== */
  function createSave(o) {
    const st = o.storage, KEY = o.key, BAK = KEY + '.bak', salt = String(o.salt || ''), now = o.now || Date.now, hooks = o.hooks || {};
    const sign = d => sha256(salt + '|' + canonical(d));
    const wrap = d => JSON.stringify({ v: VERSION, sig: sign(d), d });
    function verify(raw) {
      if (typeof raw !== 'string') return null;
      try { const w = JSON.parse(raw); if (w && w.d && typeof w.d === 'object' && w.sig === sign(w.d)) return w.d; } catch (e) {}
      return null;
    }
    const fresh = () => ({ v: VERSION, rev: 0, ledger: (o.startGems > 0 ? [{ id: 'start', kind: 'start', gems: num(o.startGems), xp: 0, day: 0, ts: now() }] : []), prog: {}, modes: {}, prefs: {}, clock: {} });
    const MIGRATIONS = {};     // MIGRATIONS[n] turns a version-n payload into version n+1
    function migrateUp(d) { while ((d.v || 1) < VERSION) { const f = MIGRATIONS[d.v || 1]; if (!f) break; d = f(d); } return d; }

    /* --- from the old, unsigned save (keys "r2lobby:xxx") into one legacy ledger entry --- */
    const OLD = 'r2lobby:';
    function legacyFrom(map) {
      const get = k => { try { const r = map[OLD + k]; return r === undefined || r === null ? undefined : JSON.parse(r); } catch (e) { return undefined; } };
      const keys = Object.keys(map).filter(k => k.indexOf(OLD) === 0);
      if (!keys.length) return null;
      const d = fresh(); d.ledger = [];
      const ts = now(), dayOf = o.dayOfIso || (() => 1), dnum = iso => Math.max(1, dayOf(iso) || 1);
      const coins = num(get('coins')), xp = num(get('xp'));
      d.ledger.push({ id: 'legacy', kind: 'legacy', gems: coins, xp, day: 0, ts });
      const mark = (id, day) => d.ledger.push({ id, kind: 'legacy-claim', gems: 0, xp: 0, day: day || 0, ts });
      const quests = get('quests') || {}, defs = o.legacyQuests || [];
      Object.keys(quests).forEach(qid => {
        const s = quests[qid] || {}, q = defs.find(x => x.id === qid), day = s.day ? dnum(s.day) : 1, once = q && !q.daily;
        if (s.claimed) mark(once ? `quest:once:${qid}` : `quest:${day}:${qid}`, day);
        else if (s.v) d.prog[qid] = { d: once ? 0 : day, v: num(s.v) };
      });
      (get('passClaimed') || []).forEach(i => mark('pass:' + i));
      const pu = get('purchases') || {};
      Object.keys(pu).forEach(id => { for (let k = 1; k <= num(pu[id]); k++) mark(`buy:${id}:${k}`); });
      const skip = ['coins', 'xp', 'quests', 'purchases', 'passClaimed', 'giftDay'];
      keys.forEach(k => { const n = k.slice(OLD.length); if (skip.indexOf(n) < 0) { const v = get(n); if (v !== undefined) d.prefs[n] = v; } });
      return d;
    }
    function legacyFromStorage() {
      if (!o.legacy) return null;
      const map = {};
      try { for (let i = 0; i < st.length; i++) { const k = st.key(i); if (k && k.indexOf(OLD) === 0) map[k] = st.getItem(k); } } catch (e) {}
      return legacyFrom(map);
    }

    /* --- read with verification, cached by raw text --- */
    let cacheRaw = null, cache = null, notice = null;
    function read() {
      const raw = st.getItem(KEY);
      if (raw !== null && raw === cacheRaw) return cache;
      let d = raw !== null ? verify(raw) : null;
      if (d) { d = migrateUp(d); cacheRaw = raw; cache = d; return d; }
      const bakRaw = st.getItem(BAK), b = verify(bakRaw);
      if (b) { notice = 'restored'; st.setItem(KEY, bakRaw); cacheRaw = bakRaw; cache = migrateUp(b); return cache; }
      if (raw !== null) notice = 'reset';
      const d2 = legacyFromStorage() || fresh(), raw2 = wrap(d2);
      st.setItem(KEY, raw2); cacheRaw = raw2; cache = d2; return d2;
    }
    const ledgerOf = d => { const seen = new Set(); return d.ledger.filter(e => e && typeof e.id === 'string' && !seen.has(e.id) && seen.add(e.id)); };

    /* --- atomic read-modify-write; retried if another tab wrote in between --- */
    const mine = [];
    function mutate(fn) {
      for (let i = 0; i < 8; i++) {
        const d0 = read(), raw0 = cacheRaw, d = clone(d0);
        d.ledger = ledgerOf(d);
        const r = fn(d); if (r && r.ok === false) return r;
        d.rev = (d.rev || 0) + 1;
        if (hooks.beforeWrite) hooks.beforeWrite();
        if (st.getItem(KEY) !== raw0) continue;
        const raw = wrap(d);
        st.setItem(BAK, raw0); st.setItem(KEY, raw);
        cacheRaw = raw; cache = d; return r || { ok: true };
      }
      return { ok: false, reason: 'busy' };
    }

    function balance() {
      let gems = 0, xp = 0;
      ledgerOf(read()).forEach(e => {
        let g = Number(e.gems) || 0;
        if (e.id === 'legacy' && o.legacyCap !== null && o.legacyCap !== undefined) g = Math.min(g, o.legacyCap);
        gems += g; xp += Number(e.xp) || 0;
      });
      return { gems: Math.max(0, Math.floor(gems)), xp: Math.max(0, Math.floor(xp)) };
    }
    const has = id => ledgerOf(read()).some(e => e.id === id);
    const countPrefix = p => ledgerOf(read()).filter(e => e.id.indexOf(p) === 0).length;

    function claim(id, spec) {
      id = String(id); spec = spec || {};
      const e = { id, kind: String(spec.kind || 'claim'), gems: num(spec.gems), xp: num(spec.xp), day: num(spec.day), ts: now() };
      const r = mutate(d => { if (d.ledger.some(x => x.id === id)) return { ok: false, reason: 'dup' }; d.ledger.push(e); return { ok: true, entry: e }; });
      if (r.ok) { mine.push(e); if (mine.length > 60) mine.shift(); }
      return r;
    }
    function spend(id, price, spec) {
      id = String(id); price = num(price); spec = spec || {};
      const e = { id, kind: String(spec.kind || 'spend'), gems: -price, xp: 0, day: num(spec.day), ts: now() };
      const r = mutate(d => {
        if (d.ledger.some(x => x.id === id)) return { ok: false, reason: 'dup' };
        if (balanceOf(d) < price) return { ok: false, reason: 'poor' };
        d.ledger.push(e); return { ok: true, entry: e };
      });
      if (r.ok) { mine.push(e); if (mine.length > 60) mine.shift(); }
      return r;
    }
    function balanceOf(d) {
      let g = 0; d.ledger.forEach(e => { let v = Number(e.gems) || 0; if (e.id === 'legacy' && o.legacyCap !== null && o.legacyCap !== undefined) v = Math.min(v, o.legacyCap); g += v; });
      return g;
    }
    /* put back anything this tab wrote that another tab's write may have overwritten */
    function reconcile() {
      if (!mine.length) return;
      const have = new Set(ledgerOf(read()).map(e => e.id)), miss = mine.filter(e => !have.has(e.id));
      if (!miss.length) return;
      mutate(d => { const ids = new Set(d.ledger.map(e => e.id)); miss.forEach(e => { if (!ids.has(e.id)) d.ledger.push(e); }); return { ok: true }; });
    }

    const getPref = (k, def) => { const p = read().prefs; return k in p ? p[k] : def; };
    function setPref(k, v) {
      if (canonical(getPref(k, undefined)) === canonical(v)) return;
      mutate(d => { d.prefs[k] = v; return { ok: true }; });
    }
    const getProg = () => read().prog;
    function setProg(id, v) { mutate(d => { d.prog[id] = v; return { ok: true }; }); }
    const getMode = id => read().modes[id] || { plays: 0, clears: 0, best: 0, stars: 0 };
    function setMode(id, fn) { mutate(d => { const m = d.modes[id] || { plays: 0, clears: 0, best: 0, stars: 0 }; fn(m); d.modes[id] = m; return { ok: true }; }); }
    const getClock = () => read().clock || {};
    function setClock(c) { if (canonical(getClock()) === canonical(c)) return; mutate(d => { d.clock = c; return { ok: true }; }); }

    /* --- backup code: the signed save, base64. Importing MERGES (never lowers anything). --- */
    function exportCode() { return b64enc(wrap(read())); }
    function importCode(code) {
      let obj, inc = null, txt;
      try { txt = b64dec(String(code).trim()); obj = JSON.parse(txt); } catch (e) { return { ok: false, reason: 'bad' }; }
      if (obj && typeof obj === 'object' && obj.sig && obj.d) inc = verify(txt);
      else if (obj && typeof obj === 'object' && Object.keys(obj).some(k => k.indexOf(OLD) === 0)) inc = o.legacy === false ? null : legacyFrom(obj);
      if (!inc) return { ok: false, reason: 'bad' };
      inc = migrateUp(inc);
      return mutate(d => {
        const ids = new Set(d.ledger.map(e => e.id));
        (inc.ledger || []).forEach(e => { if (e && typeof e.id === 'string' && !ids.has(e.id)) { d.ledger.push(e); ids.add(e.id); } });
        Object.keys(inc.modes || {}).forEach(k => { const a = d.modes[k] || { plays: 0, clears: 0, best: 0 }, b = inc.modes[k]; d.modes[k] = { plays: Math.max(a.plays, b.plays || 0), clears: Math.max(a.clears, b.clears || 0), best: Math.max(a.best, b.best || 0), stars: Math.max(a.stars || 0, b.stars || 0) }; });
        Object.keys(inc.prog || {}).forEach(k => { const a = d.prog[k], b = inc.prog[k]; if (!a || b.d > a.d || (b.d === a.d && b.v > a.v)) d.prog[k] = b; });
        Object.keys(inc.prefs || {}).forEach(k => { if (!(k in d.prefs)) d.prefs[k] = inc.prefs[k]; });
        const c = inc.clock || {}; d.clock = Object.assign({}, d.clock, { seen: !!(d.clock.seen || c.seen), hwServer: Math.max(d.clock.hwServer || 0, c.hwServer || 0), hwDevice: Math.max(d.clock.hwDevice || 0, c.hwDevice || 0) });
        return { ok: true };
      });
    }
    function wipe() { try { st.removeItem(KEY); st.removeItem(BAK); } catch (e) {} cacheRaw = cache = null; mine.length = 0; }
    const takeNotice = () => { const n = notice; notice = null; return n; };
    read();     // verifies / migrates right away
    return { read, mutate, balance, has, countPrefix, claim, spend, reconcile, getPref, setPref, getProg, setProg, getMode, setMode, getClock, setClock, exportCode, importCode, wipe, takeNotice, entries: () => ledgerOf(read()) };
  }

  /* ======================================================================
     CLOCK: server date (HEAD request) with a device-clock fallback.
     Rules: never goes backwards; once a server time was seen, the device clock
     can never unlock a new day on its own.
     o: { now(), mono(), fetchServerMs(), startMs, load(), store(state), days }
     ====================================================================== */
  function createClock(o) {
    const total = o.days || 7;
    let s = Object.assign({ seen: false, hwServer: 0, hwDevice: 0 }, o.load() || {});
    let sync = null, lastPersist = -1e9, dirty = false;
    function persist(force) {
      if (!dirty && !force) return;
      const m = o.mono(); if (!force && m - lastPersist < 60000) return;
      lastPersist = m; dirty = false;
      const other = o.load() || {};      // another tab may have moved the marks forward
      s.hwServer = Math.max(s.hwServer, other.hwServer || 0); s.hwDevice = Math.max(s.hwDevice, other.hwDevice || 0); s.seen = s.seen || !!other.seen;
      o.store({ seen: s.seen, hwServer: s.hwServer, hwDevice: s.hwDevice });
    }
    function now() {
      let t;
      if (s.seen) {
        t = sync ? sync.srv + (o.mono() - sync.mono) : s.hwServer;
        if (t > s.hwServer) { s.hwServer = t; dirty = true; }
        t = Math.max(t, s.hwServer);
      } else {
        t = Math.max(o.now(), s.hwDevice);
        if (t > s.hwDevice) { s.hwDevice = t; dirty = true; }
      }
      persist(false); return t;
    }
    async function doSync() {
      let ms = null; try { ms = await o.fetchServerMs(); } catch (e) {}
      if (!(ms > 0)) return false;
      if (ms < s.hwServer - 120000) return false;       // an old cached answer: ignore it
      const first = !s.seen;
      s.seen = true; sync = { srv: ms, mono: o.mono() }; if (ms > s.hwServer) s.hwServer = ms;
      persist(true); return first ? 'first' : true;
    }
    const rawDay = () => Math.floor((now() - o.startMs) / DAY_MS) + 1;
    const day = () => Math.max(0, Math.min(total, rawDay()));
    return {
      now, day, sync: doSync, flush: () => persist(true),
      isUnlocked: n => day() >= n,
      timeUntil: n => Math.max(0, o.startMs + (n - 1) * DAY_MS - now()),
      serverSeen: () => s.seen
    };
  }

  /* ======================================================================
     REWARD SESSIONS. A game asks start(id) for a one-time token and calls
     finish(token, {cleared, score}) at the end. common.js hands this object
     to the lobby exactly once (see R2.attach); it is never a global.
     o: { save, clock, mono, rand(), economy(), mode(id) -> {minDuration, unlockDay}|null,
          skipMin, onClear(id) }
     ====================================================================== */
  function createRewards(o) {
    const open = new Map();
    function start(id) {
      const m = o.mode(id); if (!m) return null;
      if (!o.clock.isUnlocked(m.unlockDay || 1)) return null;
      const token = Array.from({ length: 4 }, () => Math.floor(o.rand() * 4294967296).toString(36)).join('') + open.size;
      if (open.size > 20) open.delete(open.keys().next().value);
      open.set(token, { id, t0: o.mono() });
      return token;
    }
    function finish(token, res) {
      const s = typeof token === 'string' ? open.get(token) : null;
      if (!s) return { ok: false, reason: 'token' };
      open.delete(token);
      const m = o.mode(s.id); if (!m) return { ok: false, reason: 'mode' };
      const day = o.clock.day();
      if (!o.clock.isUnlocked(m.unlockDay || 1)) return { ok: false, reason: 'locked' };
      if (!o.skipMin && (o.mono() - s.t0) / 1000 < (m.minDuration || 0)) return { ok: false, reason: 'short' };
      res = res || {};
      const cleared = res.cleared === true, score = Math.min(1e7, num(res.score));
      const stars = cleared ? Math.max(0, Math.min(3, Math.floor(Number(res.stars)) || 0)) : 0;     // stars are a trophy only, they never pay Gems
      o.save.setMode(s.id, x => { x.plays++; if (cleared) x.clears++; if (score > x.best) x.best = score; if (stars > (x.stars || 0)) x.stars = stars; });
      const out = { ok: true, cleared, kind: 'none', gems: 0, xp: 0, stars, best: o.save.getMode(s.id).best };
      if (!cleared) return out;
      if (o.onClear) o.onClear(s.id);
      const eco = o.economy(), d = Math.max(1, day);
      // first clear: the share of the day's budget this mode got (budgetRewards, passed in by common.js as m.rewards.first)
      const tbl = eco.modeFirstClear || {}, fc = (m.rewards && m.rewards.first) || (tbl.gems != null ? tbl : (tbl[m.difficulty] || tbl.easy || { gems: 0, xp: 0 }));
      let r = o.save.claim(`mode:${s.id}:first`, { kind: 'mode', gems: fc.gems, xp: fc.xp, day: d });
      if (r.ok) { out.kind = 'first'; out.gems = r.entry.gems; out.xp = r.entry.xp; return out; }
      const rep = (m.rewards && m.rewards.repeat) || eco.modeRepeat;
      if (rep.dailyCap != null) {                                         // all repeat Gems of one day together stay under the cap
        const used = o.save.entries().filter(e => e.id.indexOf('mode:') === 0 && e.id.slice(-(':daily:' + d).length) === ':daily:' + d).reduce((a, e) => a + (e.gems || 0), 0);
        if (used + num(rep.gems) > rep.dailyCap) return out;
      }
      r = o.save.claim(rep.oncePerDay === false ? `mode:${s.id}:repeat:${Date.now()}` : `mode:${s.id}:daily:${d}`, { kind: 'mode', gems: rep.gems, xp: rep.xp, day: d });
      if (r.ok) { out.kind = 'daily'; out.gems = r.entry.gems; out.xp = r.entry.xp; }
      return out;
    }
    return Object.freeze({ start, finish });
  }

  /* ======================================================================
     ECONOMY: the first-clear reward of every mode, and the audit of the whole plan.
     modeDailyBudget {gems, xp} is the budget of the day a mode unlocks; it is split among the modes that unlock that day by the
     difficulty weights (easy 1, medium 1.5, hard 2), rounded to multiples of 5, one mode adjusted so the day's total is exact.
     ====================================================================== */
  const W = { easy: 1, medium: 1.5, hard: 2 };
  function split(total, weights) {
    const sum = weights.reduce((a, b) => a + b, 0), exact = weights.map(w => total * w / sum), v = exact.map(x => Math.max(5, Math.round(x / 5) * 5));
    let diff = total - v.reduce((a, b) => a + b, 0);
    while (diff !== 0) {                                              // nudge the mode whose rounding went furthest in the needed direction
      const dir = diff > 0 ? 1 : -1; let best = -1, gap = -Infinity;
      v.forEach((x, i) => { const g = (exact[i] - x) * dir; if (g > gap && (dir > 0 || x > 5)) { gap = g; best = i; } });
      v[best] += 5 * dir; diff -= 5 * dir;
    }
    return v;
  }
  function budgetRewards(modes, eco) {
    const b = eco.modeDailyBudget || { gems: 55, xp: 30 }, w = Object.assign({}, W, eco.modeWeights), out = {}, byDay = {};
    (modes || []).forEach(m => { (byDay[m.unlockDay || 1] = byDay[m.unlockDay || 1] || []).push(m); });
    Object.keys(byDay).forEach(d => {
      const list = byDay[d], ws = list.map(m => w[m.difficulty] || 1), g = split(b.gems, ws), x = split(b.xp, ws);
      list.forEach((m, i) => { out[m.id] = { gems: g[i], xp: x[i] }; });
    });
    return out;
  }
  const DAYS = 7;
  function audit(o) {
    const eco = o.economy, items = o.items, modes = (o.modes || []).slice().sort((a, b) => (a.unlockDay || 1) - (b.unlockDay || 1));
    const rewards = budgetRewards(modes, eco), first = m => (m.rewards && m.rewards.first) || rewards[m.id];
    const price = it => it.price != null ? it.price : Math.round(eco.basePrice * ((eco.rarityMultiplier || {})[it.rarity] || 1));
    const prices = items.map(price), total = prices.reduce((a, b) => a + b, 0), nq = o.questsPerDay || 3, Q = eco.dailyQuest, G = eco.dailyGift, R = eco.modeRepeat, P = eco.pass;
    const out = { prices, total, players: {}, warnings: [] };
    const who = { perfect: 'every mode cleared on its unlock day, gift, quests, pass step, repeat cap used', typical: 'gift, quests, pass; clears 7 of 10 modes (every third one never); 5 repeat Gems a day', minimal: 'gift, quests and pass only' };
    ['perfect', 'typical', 'minimal'].forEach(kind => {
      let cg = 0, cx = 0; const rows = []; let passOk = true;
      for (let d = 1; d <= DAYS; d++) {
        let g = G.gems + nq * Q.gems + (P.gems[d - 1] || 0), x = G.xp + nq * Q.xp, rep = 0;
        modes.forEach((m, i) => {
          if ((m.unlockDay || 1) !== d) return;
          if (kind === 'perfect' || (kind === 'typical' && i % 3 !== 2)) { g += first(m).gems; x += first(m).xp; }
        });
        if (kind === 'perfect') rep = R.dailyCap != null ? R.dailyCap : R.gems; else if (kind === 'typical') rep = Math.min(R.gems, R.dailyCap != null ? R.dailyCap : R.gems);
        g += rep; cg += g; cx += x;
        const need = P.xpPerStep * d, margin = cx - need; if (margin < 10) passOk = false;
        rows.push({ day: d, gems: g, xp: x, cumGems: cg, cumXp: cx, passNeed: need, margin });
      }
      const afford = prices.map(p => { const r = rows.find(x => x.cumGems >= p); return r ? r.day : null; }), all = rows.find(x => x.cumGems >= total);
      out.players[kind] = { about: who[kind], rows, afford, allDay: all ? all.day : null, left7: cg - total, passOk };
    });
    const T = out.players.typical, Pf = out.players.perfect, Mn = out.players.minimal, w = out.warnings;
    const spare = (T.rows[6].cumGems - total) / total * 100;
    if (!(spare >= 10 && spare <= 15)) w.push(`typical player ends with ${spare.toFixed(1)}% spare after buying all five (target 10-15%)`);
    if (Pf.allDay !== null && Pf.allDay < 5) w.push(`even the perfect player can own all five on Day ${Pf.allDay} (target: not before Day 5)`);
    if (Mn.allDay !== null) w.push(`the minimal player can afford all five (Day ${Mn.allDay})`);
    if (T.allDay === null) w.push('the typical player cannot afford all five by Day 7');
    ['perfect', 'typical', 'minimal'].forEach(k => { const bad = out.players[k].rows.filter(r => r.margin < 10); if (bad.length) w.push(`${k}: a pass step is not reachable with a 10 XP margin on Day ${bad.map(r => r.day).join(', ')}`); });
    out.ok = !w.length; out.spare = +spare.toFixed(1); out.rewards = rewards; return out;
  }

  return { sha256, canonical, createSave, createClock, createRewards, budgetRewards, audit, VERSION, DAY_MS };
});
