/* ==========================================================================
   Shared effects used by the lobby (Birthday Pass) and the Bazaar (gifts):
   Fx.burst(x, y)            flash + about 30 confetti / stars, gone in ~1.2 s (nothing when reduced motion is on)
   Fx.paper(letter)          the paper-style letter panel: { message, signature, image, caption }  ("\n\n" separates paragraphs)
   Fx.after(modalEl)         call once the letter is in the page (edge fade for long texts, missing pictures)
   Fx.unfold(modalEl, el)    makes the window unfold out of an element
   You do not edit this file. The styles are in common.css.
   ========================================================================== */
const Fx = (function () {
  'use strict';
  const reduced = () => !!(window.matchMedia && matchMedia('(prefers-reduced-motion: reduce)').matches);
  function burst(cx, cy) {
    if (reduced()) return;
    const layer = document.createElement('div'); layer.className = 'ps-fxlayer';
    const fl = document.createElement('div'); fl.className = 'ps-flash'; fl.style.left = cx + 'px'; fl.style.top = cy + 'px'; layer.appendChild(fl);
    const colors = ['#FFD84A', '#FF6FA8', '#6FD0FF', '#8CEB6B', '#C792FF', '#FF8A1F'];
    for (let k = 0; k < 30; k++) {
      const a = Math.random() * 6.283, d = 70 + Math.random() * 130, pc = document.createElement('span');
      pc.className = 'ps-piece' + (k % 2 ? ' star' : ''); pc.style.left = cx + 'px'; pc.style.top = cy + 'px'; pc.style.background = colors[k % colors.length];
      pc.style.setProperty('--dx', Math.cos(a) * d + 'px'); pc.style.setProperty('--dy', Math.sin(a) * d - 30 + 'px'); pc.style.setProperty('--rot', (Math.random() * 720 - 360) + 'deg');
      layer.appendChild(pc);
    }
    document.body.appendChild(layer); setTimeout(() => layer.remove(), 1300);
  }
  function paper(t) {
    t = t || {};
    const paras = String(t.message || '').split(/\n\s*\n/).map(x => x.trim()).filter(Boolean);
    const len = paras.join('').length, fs = len <= 120 ? 26 : len <= 300 ? 22 : len <= 700 ? 19 : 17;      // short letters get bigger writing
    const fig = t.image ? `<figure class="lfig"><img data-fallback src="${esc(t.image)}" alt="">${t.caption ? `<figcaption>${esc(t.caption)}</figcaption>` : ''}</figure>` : '';
    const body = paras.length ? paras.map((x, k) => `<p class="lp" style="animation-delay:${(0.15 + k * 0.35).toFixed(2)}s">${esc(x).replace(/\n/g, '<br>')}</p>`).join('') : '<p class="lp">&hellip;</p>';
    const sig = t.signature ? `<div class="lsig" style="animation-delay:${(0.3 + paras.length * 0.35).toFixed(2)}s"><svg viewBox="-12 -12 24 24"><path d="M0 8C-14-2-9-12 0-5 9-12 14-2 0 8z" fill="#E8403A" stroke="#12062F" stroke-width="2"/></svg>${esc(t.signature)}</div>` : '';
    return `<div class="paper"><div class="lscroll" style="font-size:${fs}px">${fig}${body}${sig}</div></div>`;
  }
  function after(m) {
    const sc = m.querySelector('.lscroll'); if (sc && sc.scrollHeight > sc.clientHeight + 4) sc.classList.add('fade');
    m.querySelectorAll('img[data-fallback]').forEach(im => im.addEventListener('error', () => { im.replaceWith(Object.assign(document.createElement('div'), { className: 'mnote', textContent: 'The picture is not here yet.' })); }));
  }
  function unfold(m, el) {
    if (!el) return; const rc = el.getBoundingClientRect(), mr = m.getBoundingClientRect();
    m.style.setProperty('--ux', (rc.left + rc.width / 2 - (mr.left + mr.width / 2)) + 'px'); m.style.setProperty('--uy', (rc.top + rc.height / 2 - (mr.top + mr.height / 2)) + 'px'); m.classList.add('unfold');
  }
  return { burst, paper, after, unfold };
})();
