/* ==========================================================================
   R2 the character: a drawn droid whose parts move on their own (dome, lens, body, legs),
   follows her pointer with his eye, fidgets, falls asleep, has moods and talks.
   His mind is lib/brain.js, his voice is lib/voice.js + lib/sfx.js, his words are content/phrases.js.
   Used by the lobby (big R2) and the Bazaar (small companion). You do not edit this file.
   ========================================================================== */
const R2Char = (function () {
  'use strict';
  const NS = 'http://www.w3.org/2000/svg';
  const REDUCED = !!(window.matchMedia && matchMedia('(prefers-reduced-motion: reduce)').matches);

  /* ---------- the drawing, in parts ---------- */
  function markup(uid) {
    if (CONFIG.r2Image) return `<img src="${esc(CONFIG.r2Image)}" alt="" draggable="false" data-p="img">`;
    const g = n => `url(#${uid}${n})`, O = '#1B2B5A';
    const leg = x => `
      <rect x="${x}" y="90" width="32" height="118" rx="10" fill="${g('m')}"/>
      <rect x="${x}" y="128" width="32" height="16" fill="${g('b')}"/>
      <rect x="${x + 4}" y="96" width="5" height="106" rx="2.5" fill="#fff" opacity=".55" stroke="none"/>
      <rect x="${x + 24}" y="98" width="5" height="104" rx="2.5" fill="#5C6B8E" opacity=".25" stroke="none"/>
      <rect x="${x - 10}" y="204" width="52" height="21" rx="9" fill="${g('f')}"/>
      <rect x="${x - 4}" y="207" width="22" height="4" rx="2" fill="#fff" opacity=".55" stroke="none"/>`;
    return `<svg viewBox="0 0 200 260" width="100%" height="100%" aria-hidden="true" style="display:block;overflow:visible">
    <defs>
      <linearGradient id="${uid}m" x1="0" x2="1" y1="0" y2="0"><stop offset="0" stop-color="#9DAAC4"/><stop offset=".22" stop-color="#FAFCFF"/><stop offset=".55" stop-color="#E4EAF5"/><stop offset="1" stop-color="#8794B2"/></linearGradient>
      <linearGradient id="${uid}f" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stop-color="#EEF2F9"/><stop offset="1" stop-color="#9AA7C2"/></linearGradient>
      <radialGradient id="${uid}d" cx=".36" cy=".3" r=".85"><stop offset="0" stop-color="#FFFFFF"/><stop offset=".55" stop-color="#DCE4F1"/><stop offset="1" stop-color="#8996B3"/></radialGradient>
      <linearGradient id="${uid}b" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stop-color="#5B9BFF"/><stop offset="1" stop-color="#1F55B5"/></linearGradient>
      <radialGradient id="${uid}s" cx=".4" cy=".35" r=".7"><stop offset="0" stop-color="#fff" stop-opacity=".6"/><stop offset=".45" stop-color="#fff" stop-opacity="0"/><stop offset="1" stop-color="#000" stop-opacity=".6"/></radialGradient>
      <clipPath id="${uid}cb"><rect x="50" y="62" width="100" height="136" rx="12"/></clipPath>
      <clipPath id="${uid}cd"><path d="M50 66 A50 50 0 0 1 150 66 Z"/></clipPath>
    </defs>
    <g stroke="${O}" stroke-width="3.5" stroke-linejoin="round" stroke-linecap="round" data-p="all" style="will-change:transform;transform-box:view-box;transform-origin:100px 232px">
      <g data-p="legs">
        <rect x="87" y="188" width="26" height="42" rx="7" fill="${g('m')}"/>
        <ellipse cx="100" cy="232" rx="24" ry="9" fill="${g('f')}"/>
        ${leg(22)}${leg(146)}
      </g>
      <g data-p="body" style="will-change:transform;transform-box:view-box;transform-origin:100px 198px">
        <rect x="50" y="62" width="100" height="136" rx="12" fill="${g('m')}"/>
        <g clip-path="url(#${uid}cb)" stroke="none"><rect x="124" y="62" width="26" height="136" fill="#5C6B8E" opacity=".3"/><rect x="56" y="70" width="6" height="120" rx="3" fill="#fff" opacity=".6"/></g>
        <rect x="50" y="90" width="100" height="15" fill="${g('b')}"/>
        <rect x="64" y="116" width="38" height="28" rx="3" fill="${O}"/>
        <path d="M67 124h32M67 130h32M67 136h32" stroke="#fff" stroke-width="1.5" opacity=".25"/>
        <rect x="110" y="116" width="28" height="11" rx="2" fill="${g('b')}"/>
        <rect x="110" y="131" width="28" height="11" rx="2" fill="${g('m')}"/>
        <g data-p="lights"><circle cx="76" cy="164" r="7" fill="#E63946"/><circle cx="100" cy="164" r="7" fill="#2F7BEF"/><circle cx="124" cy="164" r="7" fill="#FFD21F"/></g>
        <g fill="#fff" stroke="none" opacity=".85"><circle cx="74" cy="162" r="2"/><circle cx="98" cy="162" r="2"/><circle cx="122" cy="162" r="2"/></g>
      </g>
      <g data-p="dome" style="will-change:transform;transform-box:view-box;transform-origin:100px 66px">
        <rect x="116" y="5" width="7" height="15" rx="2" fill="${g('f')}"/>
        <path d="M50 66 A50 50 0 0 1 150 66 Z" fill="${g('d')}"/>
        <g clip-path="url(#${uid}cd)" stroke="none"><path d="M100 16 A50 50 0 0 0 50 66 L100 66 Z" fill="${g('b')}"/><rect x="122" y="12" width="32" height="56" fill="#5C6B8E" opacity=".3"/></g>
        <rect x="48" y="62" width="104" height="9" rx="4" fill="${g('f')}"/>
        <circle cx="130" cy="38" r="5.5" fill="${g('m')}"/>
        <ellipse cx="76" cy="33" rx="15" ry="7" fill="#fff" stroke="none" opacity=".6" transform="rotate(-28 76 33)"/>
        <g data-p="lens" style="will-change:transform;transform-box:view-box;transform-origin:100px 42px">
          <circle cx="100" cy="42" r="13" fill="#12224F"/>
          <circle data-p="pupil" cx="100" cy="42" r="8" fill="#E63946" stroke-width="2"/>
          <circle cx="100" cy="42" r="8" fill="${g('s')}" stroke="none"/>
          <circle cx="97" cy="39" r="2.4" fill="#fff" stroke="none" opacity=".9"/>
        </g>
      </g>
    </g></svg>`;
  }

  /* ---------- what each mood looks like ---------- */
  const LOOK = CONFIG.r2Emotions;      // every emotion is data in config.js (config.r2Emotions)
  const hex = h => [parseInt(h.slice(1, 3), 16), parseInt(h.slice(3, 5), 16), parseInt(h.slice(5, 7), 16)];
  /* each fidget is a gentle shape over 0.9-1.2 s; r2Motion.fidget scales it and it is eased in and out */
  const FIDGETS = {
    wiggle: { dur: 1.2, ease: true,  f: (p, m) => ({ rot: Math.sin(p * Math.PI * 4) * m.rot * 0.6 }) },
    spin:   { dur: 1.2, ease: true,  f: (p, m) => ({ lx: Math.sin(p * Math.PI * 3) * m.lens, dome: Math.sin(p * Math.PI * 3) * m.rot }) },
    lean:   { dur: 1.1, ease: true,  f: (p, m) => ({ rot: -Math.sin(p * Math.PI) * m.rot }) },
    rollL:  { dur: 1.2, ease: true,  f: (p, m) => ({ tx: -Math.sin(p * Math.PI) * m.move, rot: -Math.sin(p * Math.PI * 2) * m.rot * 0.4 }) },
    rollR:  { dur: 1.2, ease: true,  f: (p, m) => ({ tx: Math.sin(p * Math.PI) * m.move, rot: Math.sin(p * Math.PI * 2) * m.rot * 0.4 }) },
    nod:    { dur: 1.0, ease: true,  f: (p, m) => ({ dy: Math.sin(p * Math.PI * 2) * 2.5 }) },
    peek:   { dur: 1.5, ease: true,  f: (p, m) => ({ lx: -Math.sin(p * Math.PI) * m.lens, dome: -Math.sin(p * Math.PI) * m.rot * 1.4 }) },
    around: { dur: 1.6, ease: true,  f: (p, m) => ({ lx: Math.sin(p * Math.PI * 2) * m.lens, dome: Math.sin(p * Math.PI * 2) * m.rot }) },
    shrug:  { dur: 1.2, ease: true,  f: (p, m) => ({ dy: -Math.sin(p * Math.PI) * 3, rot: Math.sin(p * Math.PI) * m.rot * 0.3 }) },
    dance:  { dur: 1.6, ease: true,  f: (p, m) => ({ tx: Math.sin(p * Math.PI * 2) * m.move * 0.5, rot: Math.sin(p * Math.PI * 4) * m.rot * 0.5, ty: -Math.abs(Math.sin(p * Math.PI * 2)) * 3 }) },
    hop:    { dur: 0.9, ease: false, f: (p, m) => ({ ty: -4 * p * (1 - p) * m.hop })      // a parabola: eases out going up, eases in landing, one arc only
    }
  };
  const FX_LIMIT = 8;
  const CALM_MOODS = new Set(['neutral', 'happy', 'excited', 'playful', 'bored', 'dreamy', 'mischievous', 'grateful']);       // moods where he may fidget

  /* ---------- the controller ---------- */
  /* o: { buttons, phrases, name(), daysLeft(), now(), prefs:{get,set}, bus } */
  function boot(o) {
    const insts = Array.from(o.buttons).map(btn => {
      const wrap = btn.parentElement, mini = wrap.querySelector('.mini');
      const part = n => btn.querySelector(`[data-p="${n}"]`);
      const inst = {
        btn, wrap, mini, beep: mini && mini.querySelector('.beep'), hideAt: 0,
        p: { all: part('all'), legs: part('legs'), body: part('body'), dome: part('dome'), lens: part('lens'), pupil: part('pupil'), lights: part('lights'), img: part('img') },
        c: { lx: 0, ly: 0, dome: 0, domeY: 0, lean: 0, ls: 1, lsy: 1, body: 1, shake: 0, rgb: hex('#E63946') },
        gaze: { x: 0, y: 0 }, away: null, awayUntil: 0, nextAway: 4, blinkUntil: 0, nextBlink: 2, fidget: null, nextFidget: 6 + Math.random() * 6, nextFx: 0, lightsAt: 0, vis: true, lc: null, sp: 0, blinkV: 1, sk: null, lastMood: 'neutral', lastFidget: '', sad: false
      };
      if (mini) mini.classList.add('off');
      return inst;
    });
    const brain = R2Brain.create({
      phrases: (o.phrases && o.phrases.length) ? o.phrases : (CONFIG.phrases || []).map(t => ({ t, lang: 'en', mood: 'neutral', tags: ['idle', 'tap1', 'tap2'], weight: 1 })),
      now: Date.now, name: o.name, daysLeft: o.daysLeft, hour: () => parseInt(new Date(o.now()).toLocaleString('en-GB', { hour: 'numeric', hour12: false, timeZone: 'Europe/Paris' }), 10) % 24,
      onSay: say, onMood: m => { if (m !== 'sleepy') sleepSounded = 0; }
    });

    let speakingUntil = 0, sleepSounded = 0, lookEl = null, lookUntil = 0, lookXY = null, px = null, py = null, rawX = null, rawY = null, acceptedAt = 0, ema = 0, fast = 0, pointerAt = performance.now();
    let raf = 0, last = performance.now(), t = 0;

    function say(ph, ms) {
      const dur = Sfx.speak(ph.t, (LOOK[brain.mood()] || {}).voice || brain.mood());
      speakingUntil = performance.now() + dur * 1000;
      const show = Math.max(2400, ph.t.length * 90 + 1300);
      insts.forEach(i => {
        if (!i.mini || !i.beep) return;
        i.beep.textContent = ph.t; i.mini.classList.remove('off'); i.mini.classList.remove('pop'); void i.mini.offsetWidth; i.mini.classList.add('pop');
        i.hideAt = performance.now() + show;
      });
    }

    /* ---- tuning lives in config.r2Motion (and content/settings.js). Level = Calm / Normal / Lively from the menu ---- */
    const M = () => CONFIG.r2Motion;
    let level = o.prefs.get('motion', M().level), amp = 1;
    const calcAmp = () => ((M().levels || {})[level] || 1) * (REDUCED ? 0.5 : 1);        // reduced motion halves every amplitude
    amp = calcAmp();
    o.bus.on('motion', () => { level = o.prefs.get('motion', M().level); amp = calcAmp(); });
    const sm = (cur, tgt, settle, dt) => cur + (tgt - cur) * (1 - Math.exp(-dt / (settle / 3)));   // frame-rate independent smoothing; settle = seconds to arrive

    /* ---- measuring happens outside the animation loop (no layout reads inside it) ---- */
    function measure() {
      insts.forEach(i => {
        i.vis = i.btn.getClientRects().length > 0;
        if (i.vis) { const r = (i.p.lens || i.btn).getBoundingClientRect(); i.lc = [r.left + r.width / 2, r.top + r.height / 2, Math.max(160, r.width * 9)]; }
      });
    }
    setInterval(measure, 400); addEventListener('resize', measure); measure();
    function lookAt(el, ms) { if (!el) return; const r = el.getBoundingClientRect(); lookXY = [r.left + r.width / 2, r.top + r.height / 2]; lookUntil = performance.now() + (ms || 1400); }

    /* ---- particles ---- */
    function fx(i, kind) {
      if (REDUCED || i.wrap.querySelectorAll('.fx').length >= FX_LIMIT) return;
      const s = document.createElement('span'); s.className = 'fx fx-' + kind;
      s.style.left = (kind === 'steam' ? (Math.random() < 0.5 ? 28 : 68) + Math.random() * 6 : kind === 'zzz' ? 62 : kind === 'tear' ? 44 : 30 + Math.random() * 40) + '%';
      if (kind === 'heart') s.innerHTML = '<svg viewBox="-12 -12 24 24"><path d="M0 8C-14-2-9-12 0-5 9-12 14-2 0 8z" fill="#FF6FA8" stroke="#fff" stroke-width="2"/></svg>';
      else if (kind === 'zzz') s.textContent = 'Z';
      else if (kind === 'q') s.textContent = '?';
      else if (kind === 'bang') s.textContent = '!';
      else if (kind === 'sweat') { s.style.left = '64%'; s.innerHTML = '<svg viewBox="0 0 10 14"><path d="M5 1C5 1 1 7 1 9a4 4 0 0 0 8 0C9 7 5 1 5 1z" fill="#BFE3FF" stroke="#fff" stroke-width="1"/></svg>'; }
      else if (kind === 'spiral') s.innerHTML = '<svg viewBox="-12 -12 24 24"><path d="M0 0c3 0 4 3 2 5-3 3-8 0-7-5 1-6 9-8 12-2" fill="none" stroke="#fff" stroke-width="2.4" stroke-linecap="round"/></svg>';
      else if (kind === 'blush') { s.style.left = '34%'; s.innerHTML = '<svg viewBox="0 0 30 12"><ellipse cx="6" cy="6" rx="6" ry="4" fill="#FF8FB0"/><ellipse cx="24" cy="6" rx="6" ry="4" fill="#FF8FB0"/></svg>'; }
      else if (kind === 'note') s.innerHTML = '<svg viewBox="-12 -12 24 24"><path d="M-2-9L8-11V4a4 3 0 1 1-2-2.6V-6L0-5V7a4 3 0 1 1-2-2.6z" fill="#fff" stroke="#12062F" stroke-width="1.5"/></svg>';
      else if (kind === 'cloud') s.innerHTML = '<svg viewBox="-14 -10 28 20"><path d="M-8 6a5 5 0 0 1 0-10 7 7 0 0 1 13-1 5 5 0 0 1 1 11z" fill="#C9D3E8" stroke="#fff" stroke-width="1.5"/></svg>';
      else if (kind === 'spark') s.innerHTML = '<svg viewBox="-12 -12 24 24"><path d="M0-10L3-3 10 0 3 3 0 10-3 3-10 0-3-3z" fill="#FFE27A" stroke="#fff" stroke-width="1.5"/></svg>';
      else if (kind === 'tear') s.innerHTML = '<svg viewBox="0 0 10 14"><path d="M5 1C5 1 1 7 1 9a4 4 0 0 0 8 0C9 7 5 1 5 1z" fill="#8FC2FF" stroke="#fff" stroke-width="1"/></svg>';
      i.wrap.appendChild(s); setTimeout(() => s.remove(), 2400);
    }
    const burst = (i, k) => { i.sk = { t0: t, a: Math.min(2, M().shake.amp * amp * (k || 1)) }; };      // one short decaying shake, never continuous
    const f2 = n => n.toFixed(2);

    /* ---- one animation loop for the whole character ---- */
    function frame(now) {
      raf = requestAnimationFrame(frame);
      const dt = Math.min(1 / 30, (now - last) / 1000); last = now; t += dt;
      const F = M(), mood = brain.mood(), asleep = brain.asleep(), L = LOOK[mood] || LOOK.neutral;
      const blendT = Math.min(0.6, Math.max(0.3, L.blend || F.mood.blend));     // 0.3-0.6 s into any mood
      const speaking = now < speakingUntil;
      // the cursor is low-pass filtered: tiny moves are ignored and the target updates at most every ~60 ms
      if (rawX !== null && now - acceptedAt >= F.follow.updateMs && (px === null || Math.hypot(rawX - px, rawY - py) >= F.follow.deadzone)) { px = rawX; py = rawY; acceptedAt = now; }
      insts.forEach(i => { if (i.hideAt && now > i.hideAt && i.mini) { i.mini.classList.add('off'); i.hideAt = 0; } });
      if (now - pointerAt > 120) ema *= Math.exp(-dt * 6);
      if (ema > 2500) { fast += dt; if (fast > 1.2) { brain.pointerSpeed(ema); fast = 0; } } else fast = 0;

      insts.forEach(i => {
        if (!i.vis) return;
        const c = i.c, blend = blendT, sad = mood === 'sad' || mood === 'sleepy';
        if (sad !== i.sad) { i.sad = sad; i.btn.classList.toggle('m-sad', sad); }
        if (mood !== i.lastMood) { i.lastMood = mood; if (mood === 'angry') burst(i, 1); else if (mood === 'annoyed' || mood === 'laughing') burst(i, 0.5); }
        // mood colour and posture blend over ~0.45 s
        const tgt = hex(L.color); let moved = 0;
        for (let k = 0; k < 3; k++) { const n = sm(c.rgb[k], tgt[k], blend, dt); moved = Math.max(moved, Math.abs(n - c.rgb[k])); c.rgb[k] = n; }
        if (i.p.pupil && moved > 0.05) i.p.pupil.setAttribute('fill', `rgb(${c.rgb.map(Math.round).join(',')})`);
        for (const k of ['ls', 'lsy', 'dome', 'domeY', 'lean', 'body']) c[k] = sm(c[k], L[k], blend, dt);
        // blink: quick but never a snap
        if (t > i.nextBlink) { i.blinkUntil = t + 0.14; i.nextBlink = t + 3 + Math.random() * 4; }
        i.blinkV = sm(i.blinkV, (t < i.blinkUntil || asleep) ? 0.12 : 1, 0.1, dt);
        // where he looks
        if (t > i.nextAway && !asleep) { i.away = { x: (Math.random() - 0.5) * 1.6, y: -0.3 + Math.random() * 0.2 }; i.awayUntil = t + 1.2 + Math.random() * 1.2; i.nextAway = t + 8 + Math.random() * 10; }
        let gx = 0, gy = 0, target = null;
        if (lookXY && now < lookUntil) target = lookXY; else if (px !== null) target = [px, py];
        if (asleep) { gx = 0; gy = 0.6; }
        else if (i.away && t < i.awayUntil) { gx = i.away.x; gy = i.away.y; }
        else if (target && i.lc) { gx = Math.max(-1, Math.min(1, (target[0] - i.lc[0]) / i.lc[2])); gy = Math.max(-1, Math.min(1, (target[1] - i.lc[1]) / i.lc[2])); }
        if (L.gaze === 'down') gy = Math.max(gy, 0.7);
        if (L.gaze === 'up') gy = Math.min(gy, -0.5);
        i.gaze.x = sm(i.gaze.x, gx, F.follow.settle, dt); i.gaze.y = sm(i.gaze.y, gy, F.follow.settle, dt);
        // fidgets: rare, a different one each time, eased in and out
        if (!i.fidget && !asleep && t > i.nextFidget && CALM_MOODS.has(mood)) {
          const names = Object.keys(FIDGETS).filter(n => n !== i.lastFidget), name = names[Math.floor(Math.random() * names.length)];
          i.fidget = { name, t0: t }; i.lastFidget = name; i.nextFidget = t + FIDGETS[name].dur + F.fidget.minGap + Math.random() * (F.fidget.maxGap - F.fidget.minGap);
        }
        let fd = {};
        if (i.fidget) {
          const D = FIDGETS[i.fidget.name], p = (t - i.fidget.t0) / D.dur;
          if (p >= 1) i.fidget = null;
          else { const e = D.ease ? 0.5 - 0.5 * Math.cos(p * 2 * Math.PI) : 1, r = D.f(p, { rot: F.fidget.rot, move: F.fidget.move, hop: F.fidget.hop, lens: F.follow.lensMax * 1.3 }); for (const k in r) fd[k] = r[k] * e * amp; }
        }
        // idle life: a slow sine bob and a barely-there breath
        const bob = Math.sin(t * 2 * Math.PI * F.bob.hz * (asleep ? 0.6 : 1)) * F.bob.amp * amp * (asleep ? 0.6 : 1);
        const breath = 1 + Math.sin(t * 2 * Math.PI * 0.28) * 0.008 * amp;
        i.sp = sm(i.sp, speaking ? 1 : 0, 0.15, dt);
        const pulse = i.sp * F.speak.pulse * Math.sin(t * 2 * Math.PI * F.speak.hz);
        let shake = 0; if (i.sk) { const p = (t - i.sk.t0) / F.shake.dur; if (p >= 1) i.sk = null; else shake = i.sk.a * Math.exp(-3 * p) * Math.sin(p * 2 * Math.PI * F.shake.cycles); }
        // apply: transform only, via CSS on the SVG groups
        const dm = F.follow.domeMax * amp, lm = F.follow.lensMax * amp;
        if (i.p.all) {
          i.p.all.style.transform = `translate3d(${f2((fd.tx || 0) + shake)}px,${f2((fd.ty || 0) + bob)}px,0) rotate(${f2(c.lean * amp + (fd.rot || 0) + shake * 0.5)}deg)`;
          i.p.body.style.transform = `scale(1,${(c.body * breath).toFixed(4)})`;
          i.p.dome.style.transform = `translate3d(0,${f2(c.domeY * amp + (fd.dy || 0))}px,0) rotate(${f2(c.dome * amp + (fd.dome || 0) + i.gaze.x * dm)}deg)`;
          i.p.lens.style.transform = `translate3d(${f2(i.gaze.x * lm + (fd.lx || 0))}px,${f2(i.gaze.y * lm * 0.6)}px,0) scale(${(c.ls * (1 + pulse)).toFixed(3)},${(c.lsy * (1 + pulse) * i.blinkV).toFixed(3)})`;
          if (i.p.lights && t > i.lightsAt) { i.lightsAt = t + 1.5 + Math.random() * 2; const k = Math.floor(Math.random() * 3); Array.from(i.p.lights.children).forEach((n, j) => n.setAttribute('opacity', asleep ? 0.45 : (j === k && Math.random() < 0.5 ? 0.6 : 1))); }
        } else if (i.p.img) {                       // her own R2 picture: it can only tilt, float and shake
          i.p.img.style.transform = `translate3d(${f2((fd.tx || 0) + shake)}px,${f2((fd.ty || 0) + bob)}px,0) rotate(${f2(c.lean * amp + (fd.rot || 0))}deg)`;
        }
        // effect icons: which one and how often is data (config.r2Emotions)
        if (t > i.nextFx && !REDUCED) {
          const fk = asleep ? 'zzz' : L.fx;
          if (fk) fx(i, fk);
          i.nextFx = t + (fk ? (asleep ? 1.9 : (L.fxEvery || 1.4)) : 0.5);
        }
      });
      if (asleep && now - sleepSounded > 3800) { sleepSounded = now; if (!document.hidden) Sfx.snore(); }
      if (asleep === false) sleepSounded = 0;
      brain.tick(!document.hidden);
    }

    function start() { if (!raf && !document.hidden) { last = performance.now(); raf = requestAnimationFrame(frame); } }
    function stop() { cancelAnimationFrame(raf); raf = 0; }

    /* ---- input from her ---- */
    const isR2 = e => !!(e.target.closest && e.target.closest('.r2btn'));
    addEventListener('pointermove', e => {
      const n = performance.now(), dtm = n - pointerAt;
      if (rawX !== null && dtm > 0 && dtm < 200) ema = ema * 0.7 + (Math.hypot(e.clientX - rawX, e.clientY - rawY) / dtm * 1000) * 0.3;
      rawX = e.clientX; rawY = e.clientY; pointerAt = n;       // the loop filters this (dead zone + rate limit)
    }, { passive: true });
    ['pointerdown', 'keydown', 'wheel', 'touchstart'].forEach(ev => addEventListener(ev, e => { if (!isR2(e)) brain.input(); }, { capture: true, passive: true }));
    let dragPath = 0, dragging = false, dragX = 0, dragY = 0;
    addEventListener('pointerdown', e => { if (isR2(e)) { dragging = true; dragPath = 0; dragX = e.clientX; dragY = e.clientY; } }, true);
    addEventListener('pointermove', e => { if (dragging) { dragPath += Math.hypot(e.clientX - dragX, e.clientY - dragY); dragX = e.clientX; dragY = e.clientY; if (dragPath > 500) { dragging = false; brain.pointerSpeed(9999); } } }, { passive: true });
    addEventListener('pointerup', () => { dragging = false; }, true);
    document.addEventListener('click', e => {                 // when she presses something, he looks at it
      if (isR2(e)) return;
      const t = e.target;
      if (t.closest && (t.closest('button:disabled,[aria-disabled="true"]') || !t.closest('button,a,input,textarea,select,label,[data-action],.modal,.pass-root,.splash,.welcome,.r2wrap'))) o.bus.emit('ui:empty');   // disabled button or empty space: confusing
      const b = e.target.closest && e.target.closest('button,[data-action]'); if (b) lookAt(b, 1300);
    }, true);
    document.addEventListener('visibilitychange', () => {
      if (document.hidden) { brain.hidden(); o.prefs.set('lastSeen', Date.now()); stop(); }
      else { brain.shown(); start(); }
    });
    addEventListener('pagehide', () => o.prefs.set('lastSeen', Date.now()));
    setInterval(() => { if (!document.hidden) o.prefs.set('lastSeen', Date.now()); }, 60000);

    /* ---- the event bus: what happens in the app, he reacts to ---- */
    const LOOKS = { 'quest:done': '[data-action="quests"]', 'pass:open': '[data-action="pass"]', 'game:start': '[data-action="play"]' };
    Object.keys(R2Brain.EVENTS).forEach(ev => o.bus.on(ev, d => {
      brain.event(ev, d);
      const sel = LOOKS[ev]; if (sel) { const el = Array.from(document.querySelectorAll(sel)).find(x => x.getClientRects().length); if (el) lookAt(el, 1800); }
    }));

    start();
    if (o.dev) {                                    // dev only (config.devKey): step through all moods with their voice
      const box = document.createElement('div'); box.style.cssText = 'position:fixed;left:8px;bottom:8px;z-index:60;display:flex;gap:6px;align-items:center;padding:6px 8px;background:rgba(0,0,0,.7);color:#fff;font:13px monospace;border-radius:8px';
      const lab = document.createElement('span'), mk = (txt, f) => { const b = document.createElement('button'); b.type = 'button'; b.textContent = txt; b.style.cssText = 'padding:3px 8px'; b.onclick = f; return b; };
      let k = -1, auto = 0;
      const go = d => { k = (k + d + R2Brain.MOODS.length) % R2Brain.MOODS.length; const m = R2Brain.MOODS[k]; lab.textContent = (k + 1) + '/' + R2Brain.MOODS.length + ' ' + m; brain.preview(m); };
      box.append(mk('<', () => go(-1)), lab, mk('>', () => go(1)), mk('auto', function () { auto = auto ? (clearInterval(auto), 0) : setInterval(() => go(1), 4500); this.style.background = auto ? '#52C93F' : ''; }));
      document.body.appendChild(box); lab.textContent = 'mood cycler';
    }
    return {
      tap() {
        const r = brain.tap();
        if (!r.spoke) Sfx.speak(['bip', 'bop', 'biu'][r.n % 3], (LOOK[brain.mood()] || {}).voice || brain.mood());
        insts.forEach(i => { if (!i.fidget && !brain.asleep()) i.fidget = { name: 'hop', t0: t }; if (r.spoke || r.n >= 5) { const m = brain.mood(); if (m === 'angry' || m === 'annoyed') burst(i, m === 'angry' ? 1 : 0.5); } });
        return r;
      },
      greet() {                                          // when she arrives: hello by the time of day, or "where were you?"
        const lastSeen = o.prefs.get('lastSeen', 0), gap = lastSeen ? Date.now() - lastSeen : 0;
        const h = parseInt(new Date(o.now()).toLocaleString('en-GB', { hour: 'numeric', hour12: false, timeZone: 'Europe/Paris' }), 10) % 24;
        if (+o.daysLeft() <= 0 && o.birthdayToday && o.birthdayToday()) brain.event('birthday');
        else if (gap > 10 * 60000 && brain.comeBack(gap)) { /* said */ }
        else brain.hello(h);
      },
      brain
    };
  }

  return { markup, boot };
})();
