/* Content registry. Content files call R2.register(...) with plain data (strict JSON).
   common.js takes this over (and removes __r2reg) as soon as it loads. You do not edit this file. */
(function () {
  const reg = { settings: null, economy: null, quiz: null, shop: null, phrases: null, games: null, days: {}, payloads: {}, gc: {} };
  window.__r2reg = reg;
  window.R2 = {
    register(kind, a, b) {
      if (kind === 'day') reg.days[a] = b;
      else if (kind === 'payload') reg.payloads[a] = b;
      else if (kind === 'gamecontent') reg.gc[a] = b;
      else if (kind in reg) reg[kind] = a;
    }
  };
})();
