/* ==========================================================================
   Sound effects and volume control (WebAudio, nothing to download).
   Four sliders: master, music, effects, R2 voice (+ the existing mute switch).
   The browser only lets sound start after a first tap; the start screen does that (Sfx.unlock()).
   You do not edit this file.
   ========================================================================== */
const Sfx = (function () {
  'use strict';
  let ctx = null, master = null, sfxBus = null, voiceBus = null, io = null, lastHover = 0;
  const LEVELS = { master: 1, music: 1, sfx: 1, voice: 1 };
  const listeners = [];

  /* common.js hands over how to read/save settings and the mute switch */
  function bind(adapter) {
    io = adapter;
    Object.keys(LEVELS).forEach(k => { const v = io.get('vol.' + k, 1); LEVELS[k] = typeof v === 'number' ? Math.max(0, Math.min(1, v)) : 1; });
  }
  const level = k => LEVELS[k];
  function setLevel(k, v) {
    v = Math.max(0, Math.min(1, +v || 0)); LEVELS[k] = v;
    if (io) io.set('vol.' + k, v);
    if (master) { master.gain.value = LEVELS.master; sfxBus.gain.value = LEVELS.sfx; voiceBus.gain.value = LEVELS.voice; }
    listeners.forEach(f => f(k, v));
  }
  const onLevel = f => { listeners.push(f); };
  const muted = () => !!(io && io.muted());

  function ensure() {                                   // the audio context exists (suspended) from the start so custom sounds can be decoded early
    try {
      if (!ctx) {
        ctx = new (window.AudioContext || window.webkitAudioContext)();
        master = ctx.createGain(); sfxBus = ctx.createGain(); voiceBus = ctx.createGain();
        master.gain.value = LEVELS.master; sfxBus.gain.value = LEVELS.sfx; voiceBus.gain.value = LEVELS.voice;
        sfxBus.connect(master); voiceBus.connect(master); master.connect(ctx.destination);
      }
    } catch (e) {}
    return !!ctx;
  }
  function unlock() { ensure(); try { if (ctx && ctx.state === 'suspended') ctx.resume(); } catch (e) {} return !!ctx; }

  /* custom button sounds (config.sfx): decoded once into WebAudio buffers. From file:// the browser blocks fetch, so a small Audio pool is used instead */
  const custom = {}, NAMES = ['click', 'back', 'denied', 'open'];
  function loadCustom(map) {
    NAMES.forEach(n => {
      const path = map && map[n]; if (!path) return;
      const fallback = () => { const a = new Audio(path); a.preload = 'auto'; a.addEventListener('error', () => { delete custom[n]; console.warn('[sfx] could not load', path, '- using the built-in sound'); }); custom[n] = { el: a }; };
      try { fetch(path).then(r => { if (!r.ok) throw 0; return r.arrayBuffer(); }).then(b => { ensure(); return ctx.decodeAudioData(b); }).then(buf => { custom[n] = { buf }; }).catch(fallback); } catch (e) { fallback(); }
    });
  }
  function playCustom(n) {
    const c = custom[n]; if (!c) return false;
    const rate = 1 + (Math.random() - 0.5) * 0.06;     // +-3% so repeated clicks do not sound identical
    try {
      if (c.buf) { if (!unlock()) return false; const s = ctx.createBufferSource(); s.buffer = c.buf; s.playbackRate.value = rate; s.connect(sfxBus); s.start(); return true; }
      const a = c.el.cloneNode(); a.volume = Math.min(1, LEVELS.sfx * LEVELS.master); a.playbackRate = rate; a.play().catch(() => {}); return true;
    } catch (e) { return false; }
  }
  ['pointerdown', 'keydown', 'touchend'].forEach(ev => addEventListener(ev, function once() { unlock(); }, { once: true, capture: true }));

  /* one note: freq (Hz, or [from,to]), seconds, wave, volume, delay */
  function tone(freq, dur, wave, vol, delay, bus) {
    if (muted() || !unlock()) return;
    try {
      const t = ctx.currentTime + (delay || 0), o = ctx.createOscillator(), g = ctx.createGain(), f = Array.isArray(freq) ? freq : [freq, freq];
      o.type = wave || 'square'; o.frequency.setValueAtTime(f[0], t);
      if (f[1] !== f[0]) o.frequency.exponentialRampToValueAtTime(f[1], t + dur);
      g.gain.setValueAtTime(0.0001, t); g.gain.exponentialRampToValueAtTime(vol || 0.08, t + 0.008); g.gain.exponentialRampToValueAtTime(0.0001, t + dur);
      o.connect(g).connect(bus === 'voice' ? voiceBus : sfxBus); o.start(t); o.stop(t + dur + 0.02);
    } catch (e) {}
  }
  const seq = (notes, wave, vol, step, dur) => notes.forEach((n, i) => tone(n, dur || step * 1.6, wave, vol, i * step));

  const SOUNDS = {
    click:   () => tone([760, 520], 0.05, 'square', 0.05),
    back:    () => tone([520, 280], 0.08, 'square', 0.05),
    modal:   () => tone([320, 640], 0.1, 'triangle', 0.06),
    tab:     () => seq([620, 840], 'triangle', 0.05, 0.05, 0.06),
    claim:   () => seq([523, 659, 784], 'triangle', 0.08, 0.07, 0.12),
    coin:    () => seq([1318, 1760], 'square', 0.04, 0.06, 0.12),
    buy:     () => { seq([1318, 1760], 'square', 0.045, 0.06, 0.12); seq([523, 659, 784, 1047], 'triangle', 0.06, 0.08, 0.16); },
    denied:  () => seq([170, 130], 'square', 0.07, 0.09, 0.1),
    toast:   () => tone([880, 990], 0.09, 'sine', 0.05),
    levelUp: () => seq([392, 523, 659, 784, 1047], 'triangle', 0.09, 0.09, 0.2),
    hover:   () => { const n = performance.now(); if (n - lastHover < 70) return; lastHover = n; tone(1250, 0.02, 'sine', 0.012); }
  };
  function play(name) {
    if (muted()) return; const key = name === 'modal' ? 'open' : name;
    if (custom[key] && playCustom(key)) return;
    const f = SOUNDS[name]; if (f) f();
  }
  /* a button press: at most one every 40 ms */
  let lastUi = 0;
  function ui(name) { const n = performance.now(); if (n - lastUi < 40) return; lastUi = n; play(name === 'open' ? 'modal' : name); }

  /* R2 speaks: returns how long the babble lasts (seconds) so the bubble can match */
  function speak(text, mood) {
    const plan = R2Voice.plan(text, mood);
    if (muted() || !unlock()) return plan.duration;
    R2Voice.play(plan, ctx, voiceBus, 1);
    return plan.duration;
  }
  function snore() { if (muted() || !unlock()) return; tone([110, 70], 0.7, 'sine', 0.05, 0, 'voice'); }

  return { bind, unlock, level, setLevel, onLevel, play, ui, loadCustom, tone, speak, snore, muted };
})();
