/* ==========================================================================
   R2's voice: a procedural beep/whistle/warble generator (WebAudio, no sample files).
   plan(text, mood) is pure and deterministic (same phrase = same babble), so it is tested in Node.
   The player (browser only) turns a plan into sound through Sfx.voiceBus().
   You do not edit this file.
   ========================================================================== */
(function (root, factory) {
  if (typeof module === 'object' && module.exports) module.exports = factory();
  else root.R2Voice = factory();
})(typeof globalThis !== 'undefined' ? globalThis : this, function () {
  'use strict';

  /* ---- 8 gesture kinds x 6 parameter presets = 48 distinct variants ---- */
  const KINDS = ['chirpUp', 'chirpDown', 'warble', 'whistle', 'raspberry', 'blip', 'bell', 'squeak'];
  const PRESETS = [
    { base: 520,  wave: 'triangle', fm: 1,   idx: 0.4, glide: 1.8 },
    { base: 760,  wave: 'sine',     fm: 2,   idx: 1.2, glide: 2.4 },
    { base: 1100, wave: 'square',   fm: 1.5, idx: 0.8, glide: 1.5 },
    { base: 380,  wave: 'sawtooth', fm: 3,   idx: 1.6, glide: 2.0 },
    { base: 1500, wave: 'triangle', fm: 4.2, idx: 2.2, glide: 1.3 },
    { base: 640,  wave: 'sine',     fm: 0.5, idx: 1.0, glide: 3.0 }
  ];
  const VARIANTS = [];
  KINDS.forEach(k => PRESETS.forEach((p, i) => VARIANTS.push(Object.assign({ id: k + i, kind: k }, p))));

  /* mood -> pitch, speed, loudness, which gestures he likes, and how a phrase ends */
  const PROFILE = {
    neutral:   { pitch: 1.0,  speed: 1.0,  vol: 1.0,  like: { chirpUp: 2, chirpDown: 2, warble: 2, whistle: 1, blip: 3, bell: 1, squeak: 1, raspberry: 0.2 } },
    happy:     { pitch: 1.25, speed: 1.2,  vol: 1.0,  like: { chirpUp: 4, warble: 2, whistle: 3, blip: 2, bell: 2, squeak: 2, chirpDown: 0.5 } },
    love:      { pitch: 1.15, speed: 0.8,  vol: 0.9,  like: { warble: 4, whistle: 4, bell: 2, chirpUp: 1 } },
    curious:   { pitch: 1.2,  speed: 1.0,  vol: 0.95, like: { chirpUp: 4, warble: 2, whistle: 2, squeak: 1, blip: 1 }, end: 'up' },
    surprised: { pitch: 1.5,  speed: 1.5,  vol: 1.1,  like: { squeak: 5, chirpUp: 3, blip: 2 } },
    shy:       { pitch: 1.3,  speed: 0.8,  vol: 0.55, like: { whistle: 3, squeak: 2, blip: 2, warble: 1 } },
    sleepy:    { pitch: 0.7,  speed: 0.55, vol: 0.6,  like: { chirpDown: 4, warble: 2, whistle: 1 }, end: 'down' },
    proud:     { pitch: 1.0,  speed: 0.9,  vol: 1.0,  like: { bell: 4, chirpUp: 2, blip: 2, whistle: 2 } },
    laughing:  { pitch: 1.3,  speed: 1.6,  vol: 1.0,  like: { blip: 5, squeak: 3, chirpUp: 2 }, laugh: true },
    sad:       { pitch: 0.75, speed: 0.65, vol: 0.8,  like: { chirpDown: 5, warble: 2, whistle: 1 }, end: 'down' },
    annoyed:   { pitch: 0.85, speed: 1.25, vol: 1.0,  like: { raspberry: 4, blip: 3, chirpDown: 2 } },
    excited:     { ascend: true, pitch: 1.4,  speed: 1.5,  vol: 1.05, like: { chirpUp: 5, squeak: 3, whistle: 2, blip: 3, bell: 2 } },
    dreamy:      { pitch: 1.05, speed: 0.7,  vol: 0.75, like: { whistle: 5, warble: 4, bell: 2 } },
    mischievous: { tail: 'giggle', pitch: 1.1,  speed: 1.1,  vol: 0.85, like: { warble: 3, blip: 3, squeak: 2, raspberry: 1.5 } },
    confused:    { twoTone: true, pitch: 1.15, speed: 0.9,  vol: 0.85, like: { warble: 4, chirpUp: 2, chirpDown: 2, squeak: 1 }, end: 'up' },
    worried:     { pitch: 1.1,  speed: 1.1,  vol: 0.8,  like: { warble: 3, chirpDown: 2, squeak: 2, blip: 2 } },
    grateful:    { ascend: true, pitch: 1.1,  speed: 0.85, vol: 0.9,  like: { bell: 4, whistle: 3, warble: 3 } },
    bored:       { tail: 'sigh', pitch: 0.8,  speed: 0.6,  vol: 0.65, like: { chirpDown: 3, raspberry: 2, warble: 1 }, end: 'down' },
    playful:     { pitch: 1.3,  speed: 1.3,  vol: 1.0,  like: { blip: 4, squeak: 3, warble: 3, chirpUp: 2, raspberry: 1 } },
    determined:  { pitch: 0.95, speed: 1.15, vol: 1.05, like: { blip: 5, bell: 3, chirpUp: 1 } },                       // short firm beeps
    jealous:     { pitchPool: [0.62, 0.7, 0.78], speed: 0.85, vol: 0.85, like: { raspberry: 3, chirpDown: 4, warble: 1, blip: 1 }, tail: 'sniff' },      // low grumble + a sniff
    embarrassed: { pitchPool: [1.45, 1.55, 1.65], speed: 1.3, vol: 0.7, like: { squeak: 5, blip: 3, warble: 2 }, tail: 'giggle' },                            // squeaky giggle
    scared:      { pitchPool: [1.3, 1.4, 1.5], speed: 1.9, vol: 0.9, like: { warble: 5, squeak: 3, blip: 3, chirpUp: 1 } },                                   // fast trembling beeps
    dizzy:       { pitchPool: [0.95, 1.05, 1.15], speed: 0.9, vol: 0.9, like: { warble: 5, chirpUp: 2, chirpDown: 2 }, alt: true },                           // wobbly sweeps
    flirty:      { pitchPool: [1.15, 1.25, 1.35], speed: 0.85, vol: 0.85, like: { whistle: 5, warble: 2, chirpUp: 2, bell: 1 }, end: 'up' },                // playful whistle
    angry:     { pitch: 0.55, speed: 1.5,  vol: 1.15, like: { raspberry: 6, blip: 2, chirpDown: 2 } }
  };

  function seedFrom(str) {            // 32-bit string hash
    let h = 2166136261 >>> 0;
    for (let i = 0; i < str.length; i++) { h ^= str.charCodeAt(i); h = Math.imul(h, 16777619) >>> 0; }
    return h;
  }
  function rng(seed) { let a = seed >>> 0; return () => { a = (a + 0x6D2B79F5) >>> 0; let t = a; t = Math.imul(t ^ (t >>> 15), t | 1); t ^= t + Math.imul(t ^ (t >>> 7), t | 61); return ((t ^ (t >>> 14)) >>> 0) / 4294967296; }; }

  /* A plan = list of { t, dur, variant, freq, vol }. The babble length follows the phrase length. */
  function plan(text, mood) {
    const pr = PROFILE[mood] || PROFILE.neutral, r = rng(seedFrom(String(text) + '|' + mood));
    const letters = String(text).replace(/[^\p{L}\p{N}]/gu, '').length;
    const count = Math.max(2, Math.min(40, Math.round(letters / 2.3)));
    const q = /\?\s*$/.test(text), ex = /!\s*$/.test(text);
    const pool = pr.pitchPool || [0.92, 1, 1.08].map(x => x * pr.pitch), pitch = pool[Math.floor(r() * pool.length)];   // at least 3 variants of every style
    const out = []; let t = 0;
    const weights = VARIANTS.map(v => pr.like[v.kind] || 0.15);
    let wsum = 0; weights.forEach(w => wsum += w);
    let prev = null;
    for (let i = 0; i < count; i++) {
      let x = r() * wsum, vi = 0; for (let k = 0; k < weights.length; k++) { x -= weights[k]; if (x <= 0) { vi = k; break; } }
      if (prev === vi) vi = (vi + 1 + Math.floor(r() * 5)) % VARIANTS.length;       // never the same sound twice in a row
      prev = vi;
      const v = VARIANTS[vi];
      let dur = (0.065 + r() * 0.07) / pr.speed;
      if (v.kind === 'whistle' || v.kind === 'warble') dur *= 1.6;
      const gap = (0.012 + r() * 0.03) / pr.speed;
      let freq = v.base * pitch * (0.85 + r() * 0.35);
      if (pr.ascend) freq *= 1 + 0.045 * i;                // rising warbles / chime-chirps
      if (pr.alt) freq *= i % 2 ? 0.8 : 1.2;                // wobble
      if (pr.twoTone) freq *= i % 2 ? 1.26 : 1;             // two-tone question
      const last = i === count - 1;
      if (last && (q || pr.end === 'up')) freq *= 1.35;
      if (last && pr.end === 'down' && !q) freq *= 0.8;
      out.push({ t, dur, variant: v.id, kind: v.kind, wave: v.wave, fm: v.fm, idx: v.idx, glide: v.glide, freq, vol: pr.vol * (ex && last ? 1.2 : 1) * (0.8 + r() * 0.25) });
      t += dur + gap;
    }
    if (pr.laugh) {                         // ha-ha-ha tail: quick falling blips
      let f = 900 * pitch;
      for (let i = 0; i < 5; i++) { out.push({ t, dur: 0.06, variant: 'laugh' + i, kind: 'blip', wave: 'square', fm: 1, idx: 0.3, glide: 0.7, freq: f, vol: 0.8 }); t += 0.09; f *= 0.9; }
    }
    const blip = (f, d, v) => { out.push({ t, dur: d, variant: 'tail-' + pr.tail, kind: 'blip', wave: 'square', fm: 1, idx: 0.3, glide: 1, freq: f, vol: v }); t += d + 0.03; };
    if (pr.tail === 'sniff') { blip(1500 * pitch, 0.045, 0.6); blip(1700 * pitch, 0.045, 0.5); }
    if (pr.tail === 'giggle') { let f = 1100 * pitch; for (let i = 0; i < 4; i++) { blip(f, 0.05, 0.55); f *= i % 2 ? 0.92 : 1.12; } }
    if (pr.tail === 'sigh') { out.push({ t, dur: 0.5, variant: 'tail-sigh', kind: 'chirpDown', wave: 'sine', fm: 1, idx: 0.3, glide: 2.6, freq: 520 * pitch, vol: 0.7 }); t += 0.5; }
    return { items: out, duration: t, mood };
  }

  /* ---- player (browser) ---- */
  function play(p, ctx, dest, level) {
    if (!ctx) return 0;
    const t0 = ctx.currentTime + 0.02;
    p.items.forEach(it => {
      const s = t0 + it.t, e = s + it.dur, vol = 0.07 * it.vol * level;
      const o = ctx.createOscillator(), g = ctx.createGain();
      o.type = it.wave;
      const f0 = it.freq, f1 = Math.max(60, it.freq * (it.kind === 'chirpDown' ? 1 / it.glide : it.kind === 'chirpUp' || it.kind === 'squeak' ? it.glide : 1));
      o.frequency.setValueAtTime(f0, s);
      if (it.kind === 'blip' || it.kind === 'bell') o.frequency.setValueAtTime(f0, e); else o.frequency.exponentialRampToValueAtTime(f1, e);
      let mod = null;
      if (it.kind === 'warble' || it.kind === 'whistle' || it.kind === 'bell' || it.kind === 'raspberry') {   // FM / vibrato / tremolo
        mod = ctx.createOscillator(); const mg = ctx.createGain();
        mod.frequency.value = it.kind === 'raspberry' ? 38 + it.fm * 6 : it.kind === 'bell' ? f0 * it.fm : 9 + it.fm * 3;
        mg.gain.value = it.kind === 'bell' ? f0 * it.idx * 0.5 : it.kind === 'raspberry' ? f0 * 0.35 : f0 * 0.05 * it.idx;
        mod.connect(mg); mg.connect(o.frequency); mod.start(s); mod.stop(e + 0.02);
      }
      g.gain.setValueAtTime(0.0001, s); g.gain.exponentialRampToValueAtTime(Math.max(0.0002, vol), s + Math.min(0.012, it.dur / 3));
      g.gain.exponentialRampToValueAtTime(0.0001, e);
      o.connect(g).connect(dest); o.start(s); o.stop(e + 0.02);
    });
    return p.duration;
  }

  return { plan, play, VARIANTS, KINDS, PRESETS, PROFILE, seedFrom };
});
